app/Http/Controllers/v1/UserController.php, app/Http/Requests/DeleteUserRequest.php, app/Http/Requests/StoreUserRequest.php, app/Http/Requests/UpdateUserRequest.php, app/Http/Resources/NewUserResource.php, app/Http/Resources/UserResource.php, app/Models/User.php, routes/api.php, routes/web.php, tests/Feature/UserControllerTest.php
Tests are included for the controller 
TODO: add pagination and sorting for Index, look into middleware
=> User crud UN-140

database/seeders/DatabaseSeeder.php, resources/js/Components/LeftMenu.tsx, resources/js/common.ts
Adds new feature that pulls categories from the database and renders these categories and its links in the left menu.
=> Pulls and renders categories in left menu

app/Http/Controllers/v1/CourseController.php, app/Http/Requests/StoreCourseRequest.php, app/Http/Requests/UpdateCourseRequest.php, app/Http/Resources/CourseResource.php, app/Models/Course.php, database/factories/CourseFactory.php, database/seeders/CourseSeeder.php, routes/api.php, tests/Feature/CourseControllerTest.php
This is Corey's  PR for UN-210, he had some permission issues with docker/sail on his computer and it turned into quite a nightmare.
I reviewed it in the process, and I just implemented the fixes, but might still want another pair of eyes just to be sure :+1:
=> feat: add course controller/model/factory Corey UN-210

resources/js/Components/PageNav.tsx, resources/js/Pages/LeftMenuManagement.tsx, routes/web.php
Adds a new page to be able to edit left menu categories and their links. Navigation added to top right dropdown under user profile. Displays categories and their links and gives admin the ability to add and delete links (this does not yet update the database).
=> Creates left menu management page and ability to edit category links

app/Services/CanvasServices.php, database/seeders/DefaultAdmin.php, docker-compose.yml
dont know why this reformatted :eyes: 
anyway, this is the proper configuration to get docker to output mysql logs to the agreed upon directory @corypride
=> assorted fixes: add logging config dev environment, canvas services and seeder fixes

.github/deploy.sh, .github/workflows/ci.yml
This is testing the auto deployment script
=> feat: add auto deploy github action

package-lock.json, package.json, resources/js/Components/forms/AddUserForm.tsx, resources/js/Pages/Users.tsx
I would love to get rid of the user of 'alert' in the future, but going with it for the demo.
=> Add user form

app/Http/Controllers/v1/UserActivityController.php, tests/Feature/UserActivityTest.php
Requested by Carolina to search by user name, also removed search by browser.
=> fix: implement user activity search by user_name

README.md
This is a test to see if creating a pull request triggers the Jira automation to transition the corresponding Jira issue to Review status.
=> chore(UN-270): test Jira issue review transition automation

resources/js/Components/CategoryItem.tsx, resources/js/Components/PrimaryButton.tsx, resources/js/Components/SecondaryButton.tsx, resources/js/Pages/LeftMenuManagement.tsx
A batch of small and practical UI fixes.
=> Frontend fixes

resources/js/Components/forms/ResetPasswordForm.tsx, resources/js/Pages/ProviderPlatformManagement.tsx, resources/js/Pages/Users.tsx
fix: doesn't allow reset password for admin users and adds timeout for smoother transition on close of the modal
=> Small bug fixes on user page

composer.json, composer.lock, phpstan.neon
This will help for this issue https://github.com/UnlockedLabs/UnlockEdv2/issues/191
How to use : 
```
./vendor/bin/phpstan analyse --memory-limit=2G
```
At level 0, some errors are already detected : 
```
ka@mbp UnlockEdv2 % ./vendor/bin/phpstan analyse --memory-limit=2G
Note: Using configuration file /Users/ka/Repositories/UnlockEdv2/phpstan.neon.
97/97 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ ---------------------------------------------------------------------------- 
Line   Http/Controllers/v1/UserCourseActivityController.php                        
------ ---------------------------------------------------------------------------- 
25     Relation 'enrollment' is not found in App\Models\UserCourseActivity model.  
49     Relation 'enrollment' is not found in …
```
=> chore: add larastan package for linting

resources/js/Components/UserActivityMap.tsx, resources/js/Components/inputs/DropdownControl.tsx, resources/js/Components/inputs/index.js, resources/js/Pages/Dashboard.tsx, tailwind.config.js
Colors defined in tailwind.config in existing daisyui themes.
Responsiveness by listening to window resize event and adjusting size to 1 of 3 breakpoints.
DaisyUI tooltips.
Large amount of code for a front end component, but nothing too resource hungry that I can tell.
Open to any adjustments to make this best fit with the UnlockEdv2 platform.
=> feat (183): User Activity Map

app/Http/Controllers/v1/UserActivityMapController.php, resources/js/Components/UserActivityMap.tsx
Also adds the frontend display for when the activity map is loading or there is an error in loading. Keeps the block the same size to not mess up formatting of other elements around it
=> fix: fixes User Activity controller when no activity present

backend/src/database/facilities.go, backend/src/database/outcomes.go, backend/src/database/users.go, backend/src/handlers/auth.go, backend/src/handlers/facilities_handler.go, backend/tests/facilities_test.go, frontend/src/Pages/UserActivity.tsx
Some fixes I overlooked when merging our massive PR's over the weekend. added some tests as well
=> fix: user activity page link, add tests, random fixes from PR

README.md, backend/src/models/provider_platforms.go, provider-middleware/README.md, provider-middleware/main.go, provider-middleware/middleware.go
documentation for provider middleware + a couple small fixes
=> docs: add common issues to readme, fix provider middleware readme

frontend/src/Components/UserActivityMap.tsx, frontend/src/Components/inputs/DropdownControl.tsx, frontend/src/Components/inputs/SearchBar.tsx, frontend/src/Components/inputs/index.js, frontend/src/Pages/CourseCatalog.tsx, frontend/src/Pages/Users.tsx
I didn't need to do a component for dropdowns to set order - the DropdownControl component should cover this nicely.
=> feat(266): Create a general component for search

frontend/src/Components/ConvertSeconds.tsx, frontend/src/Components/MonthActivityChart.tsx, frontend/src/Components/WeeklyActivity.tsx, frontend/src/Pages/StudentDashboard.tsx
New activity graph using recharts. Closes #263
=> feat: adds activity graph on student dash

backend/src/database/activity.go
Course progress was calculated differently previously - switches to the way course progress is calculated in my courses page
=> fix: corrects recent activities course_progress on student dash

frontend/src/Components/CategoryItem.tsx, frontend/src/Components/MilestonesBarChart.tsx, frontend/src/Components/ProviderCard.tsx, frontend/src/Pages/StudentDashboard.tsx
fixes
- not showing names in milestones chart
- weird formatting for resource mgmt and prov platform cards
- grid cols for student dashboard when enrolled in 0 courses
=> fix: small UI fixes for staging

backend/src/database/activity.go, backend/src/models/program.go, frontend/src/Components/CategoryItem.tsx, frontend/src/Components/MilestonesBarChart.tsx, frontend/src/Components/ProviderCard.tsx, frontend/src/Components/StatsCard.tsx, frontend/src/Components/TopProgActivityPieChart.tsx, frontend/src/Pages/AdminDashboard.tsx, frontend/src/Pages/MyProgress.tsx, frontend/src/Pages/StudentDashboard.tsx, frontend/src/css/app.css
=> More UI fixes

backend/src/database/users.go, frontend/src/Components/CatalogCourseCard.tsx, frontend/src/Components/EnrolledCourseCard.tsx, frontend/src/Components/ResourcesSideBar.tsx
fixes:
- externally links to Kolibri
- fixes external links in my courses and course catalog
- user page pagination shows correct pages now
=> UI Fixes Pt3

frontend/src/Components/inputs/SubmitButton.tsx
@PThorpe92 Would you be able to check that this works on Firefox to make sure this fixes the issue?
Closes #324
=> fix: ensures all modal buttons are submit not submit query

frontend/src/Components/CategoryItem.tsx, frontend/src/Components/Modal.tsx, frontend/src/Components/forms/ConfirmImportAllUsersForm.tsx, frontend/src/Pages/ProviderPlatformManagement.tsx, frontend/src/Pages/ProviderUserManagement.tsx, frontend/src/Pages/ResourcesManagement.tsx, frontend/src/Pages/Users.tsx
Confirm bulk import is set to our theme rather than previous pop up. Also fixes specifications with modal types. Closes #329.
=> feat: adds confirm bulk import modal, fixes modal types

frontend/src/Components/inputs/SubmitButton.tsx
fix #336 
Spelling Correction "Sumbit" -> "Submit"
=> fix: submit button value #336

backend/src/database/users.go, backend/src/handlers/user_handler.go, frontend/src/Components/forms/AddUserForm.tsx, frontend/src/Components/forms/EditUserForm.tsx
Thank you everyone for your support with this commit.
Also thank you Preston, for showing me that all I had to do was use 127.0.0.1 instead of localhost.  I can't believe how easy that was.
=> fix: Validation error when creating preexisting username revised

frontend/src/Pages/CourseCatalog.tsx
Also adds in an error message if search does not find any results or if data cannot be loaded. Closes #333
=> fix: fixes entire page re-render for course catalog

frontend/src/Components/CatalogCourseCard.tsx
=> refactor: removed commented code

backend/Dockerfile, backend/seeder/main.go, backend/src/database/provider_platforms.go, backend/src/database/users.go, backend/src/handlers/provider_user_management.go, backend/src/models/facilities.go
these were all fixes required for the demo to go off smoothly
=> demo fixes

frontend/src/Components/TopProgActivityPieChart.tsx, frontend/src/Pages/AdminDashboard.tsx, frontend/src/Pages/StudentDashboard.tsx
Removes calendar UI for demo instance, returns it to previous state
- **Related issues**: Closes #393
=> fix: removes calendar from student and admin portal frontend

backend/src/database/courses.go, backend/src/database/provider_user_mappings.go, backend/src/database/section_enrollments.go, backend/src/database/users.go, backend/src/handlers/milestones_handler_test.go, backend/src/handlers/provider_user_management_test.go, backend/src/handlers/section_enrollments_test.go, backend/src/handlers/user_handler.go, backend/src/handlers/user_handler_test.go, frontend/src/Components/Navbar.tsx, frontend/src/Pages/AdminDashboard.tsx, frontend/src/Pages/AdminManagement.tsx, frontend/src/Pages/StudentDashboard.tsx, frontend/src/Pages/StudentManagement.tsx, frontend/src/app.tsx
=> 382 split user management into students and admins

backend/src/database/DB.go, backend/src/database/libraries.go, backend/src/handlers/libraries_handler.go, backend/src/handlers/libraries_handler_test.go, backend/src/handlers/server.go, backend/src/handlers/test_data/libraries.json, backend/src/handlers/test_data/open_content.json
Adds apis and tests for the libraries api.
- **Related issues**: Closes #399
=> feat: add libraries api and tests

backend/src/database/provider_platforms.go, backend/src/database/provider_user_mappings.go, backend/src/models/provider_platforms.go, backend/src/models/provider_platforms_test.go, provider-middleware/canvas.go
middleware isn't working properly, turns out we were doing this by hand instead of handling it automatically in hooks. I included some tests
=> Provider key fix

frontend/src/Components/PageNav.tsx, frontend/src/Components/ULIComponent.tsx
heroIcon refactor and link removal
Closes #412
=> PageNav dropdown updates #412

frontend/src/Pages/AdminManagement.tsx, frontend/src/Pages/StudentManagement.tsx
UI updates on student and admin management pages to include table-2 functionality
closes #395
=> feat: updated to use table-2

frontend/src/Pages/ResourcesManagement.tsx
=> fix: first collection shows in modify section

backend/seeder/main.go, backend/src/database/DB.go, backend/src/database/courses.go, backend/src/database/facilities.go, backend/src/database/outcomes.go, backend/src/database/program_sections.go, backend/src/database/programs.go, backend/src/database/provider_platforms.go, backend/src/database/section_events.go, backend/src/database/users.go, backend/src/handlers/actions.go, backend/src/handlers/auth.go, backend/src/handlers/facilites_handler_test.go, backend/src/handlers/facilities_handler.go, backend/src/handlers/ory.go, backend/src/handlers/provider_platform_handler.go, backend/src/handlers/provider_platform_handler_test.go, backend/src/handlers/provider_user_management.go, backend/src/handlers/provider_user_mapping_handler_test.go, backend/src/handlers/server.go, backend/src/handlers/user_handler.go, backend/src/handlers/user_handler_test.go, backend/src/models/facilities.go, backend/src/models/users.go, frontend/src/Components/forms/AddUserForm.tsx, frontend/src/Components/forms/EditProviderForm.tsx, frontend/src/Components/forms/EditUserForm.tsx, frontend/src/Components/forms/LoginForm.tsx, frontend/src/Pages/ResourcesManagement.tsx, frontend/src/api/api.ts
=> fix: student and admin management ui, remove extra tabs on my courses

frontend/src/Pages/AdminManagement.tsx, frontend/src/Pages/ResourcesManagement.tsx, frontend/src/Pages/StudentManagement.tsx
=> feat: added headers to all pages with px-8

provider-middleware/brightspace.go
@PThorpe92 Defined the interface for the brightspace provider service with all the necessary parameters to make calls to the provider.
=> #2 Brightspace Integration 

provider-middleware/brightspace.go, provider-middleware/brightspace_data.go
@PThorpe92 Defined the initial models for the expected data that will be returned so the CSV or json can be deserialized into these models. Also, added some additional utility methods that will be used.
Plan on using the following go library for parsing CSVs "github.com/gocarina/gocsv".
=> #1 Brightspace Integration

provider-middleware/kolibri_data.go
@PThorpe92 Modify anonymous struct within UploadImage method so that it correctly parses http response.
=> Issue with parsing image url response (Kolibri)

provider-middleware/brightspace.go, provider-middleware/brightspace_data.go
@PThorpe92 Initial implementation of ImportMilestones for BrightspaceService. Retrieves CSV from Brightspace REST API, parses the CSV into UnlockEd type milestone (enrollments, assignments submitted/graded, and quizzes submitted/graded).
- **Related issues**: Part of #429
=> #5 Impl ImportMilestones for BrightspaceService

backend/migrations/00014_make_drop_create_insert_daily_activity.sql, backend/migrations/00017_drop_create_insert_daily_activity_sql.sql, provider-middleware/brightspace.go, provider-middleware/brightspace_data.go
@PThorpe92 Initial implementation of ImportActivityForCourse for BrightspaceService. Retrieves CSV from Brightspace REST API, parses the CSV into UnlockEd type activity. Modified SQL function named insert_daily_activity to handle total time and time delta calculations correctly for Brightspace type activities.
- **Related issues**: Part of #429
=> #6 Impl ImportActivityForCourse for BrightspaceService

backend/src/database/activity.go, backend/src/database/libraries.go, backend/src/database/seed_demo.go, backend/src/handlers/auth.go, backend/src/handlers/feature_access.go, backend/src/handlers/libraries_handler.go, backend/src/handlers/milestones_handler.go, backend/src/handlers/user_handler.go, backend/src/handlers/user_handler_test.go, frontend/src/Components/Navbar.tsx, frontend/src/Components/forms/ConfirmSeedDemoData.tsx
=> feat: add system admin option to seed data for demo environment

frontend/src/Pages/MyProgress.tsx
Description of the change
- Removed Program Attendance table and made its with full
**Related issues**:
- Closes: #510 
-
=> refactor: Remove 'Program Attendance' table from MyProgress page

frontend/src/Components/LibraryCard.tsx, frontend/src/Components/LibraryLayout.tsx, frontend/src/Components/cards/OpenContentCard.tsx, frontend/src/Pages/OpenContentLevelDashboard.tsx, frontend/src/routeLoaders.ts
- adds featured library view to the open content dashboard
- fixes bug where cursor doesn't turn into a pointer in the dashboard
- **Related issues**: Closes #507,  Closes #544
=> feat: add featured library on dash, fix cursor pointer hover bug

frontend/src/Components/LibraryCard.tsx, frontend/src/Components/LibraryLayout.tsx, frontend/src/Components/VideoContent.tsx, frontend/src/Components/cards/HelpfulLinkCard.tsx, frontend/src/Components/cards/OpenContentCard.tsx, frontend/src/Pages/Favorites.tsx, frontend/src/Pages/HelpfulLinksManagement.tsx, frontend/src/Pages/OpenContentLevelDashboard.tsx, frontend/src/Pages/VideoManagement.tsx, frontend/src/routeLoaders.ts
- **Related issues**: Closes #557 and closes #564 and closes #565 and closes #568
=> fix: update union to include only having, text doesn't overlap flag

frontend/src/Components/Navbar.tsx
dashboard -> Learning Path  for students
=> Dashboard Name Change

frontend/src/Components/Navbar.tsx, frontend/src/useAuth.ts
added conditionals to the dashboard label
https://github.com/user-attachments/assets/e1889e15-ea96-4ddd-921f-44007a92038d
=> Dashboard label logic 

backend/src/database/seed_demo.go
Corrected the logic to account for descending dates.  Also changed random time to be 5000 rather than 50.
=> fix: correct logic for descending date

backend/src/database/helpful_links.go, backend/src/database/libraries.go, backend/src/database/videos.go, backend/src/handlers/helpful_links_handler.go, frontend/src/Components/LibraryLayout.tsx, frontend/src/Pages/HelpfulLinksManagement.tsx, frontend/src/Pages/VideoManagement.tsx, frontend/src/common.ts
Make uniform the sorting options across the Knowledge center. 
All three tabs should use the drop-down control and include the following values for sorting:
Most Popular
Title (A to Z)
Title (Z to A)
Date Added (Newest First)
Date Added (Oldest First)
- **Related issues**: #613 
https://github.com/user-attachments/assets/50c36c06-4125-4bd7-bf72-8c8f61f88539
https://github.com/user-attachments/assets/afecf069-23cd-4839-9e50-afa0807597c6
=> Sorting options and clarity in the Knowledge Center

backend/src/handlers/user_handler.go, backend/src/handlers/user_handler_test.go, provider-middleware/video_dl.go
fix hardcoded aws region, keep `username`'s immutable and add tests for that.
=> remove hardcoded aws region and prevent username changes

frontend/src/Pages/FacilityManagement.tsx
Fixes the page nav facility component so that it re-validates the loader data upon any updates of the facilities. 
- **Related issues**: Closes #637 
https://www.loom.com/share/46f06d7ff79547a0b28d123ac2f318f6?sid=a0b1d4af-d232-44ae-b283-b84eacec262a
=> fix: fix facility list item in page nav

frontend/src/Components/Pagination.tsx, frontend/src/Pages/VideoManagement.tsx
Made the pager control reflect the number of options that are multiples of 4 (12,24,60,120)
- **Related issues**: 
-  Closes #618 
- 
https://github.com/user-attachments/assets/1f73ada1-218f-4b08-8910-76946b7a1561
=> Knowledge Center - Videos - Pager control fix 

frontend/src/Components/Navbar.tsx, frontend/src/Pages/AdminLayer1.tsx, frontend/src/common.ts
Fixes the issue with the Navbar when the window is minimized, it adds scrolling ability in the links, and locks in the icon and user name component at the bottom of the navbar. 
- **Related issues**: Closes #636 
https://www.loom.com/share/846b8f5815d041868617b0398970d7a5?sid=569953b4-9a98-4336-b27b-6ed8d74d05e1
=> fix: fix navbar issues when screen is smaller

frontend/src/Components/LibrarySearchResultsModal.tsx
Missed a line of javascript when fixing merge conflicts.
- **Related issues**: Link to related issue(s) this PR addresses, related to #676.
=> fix: add missed merge line of javascript

backend/migrations/00031_alter_open_content_favorites_table.sql
Wrote alter SQL script to fix the constraint issues when admins features the same library from multiple facilities.
- **Related issues**: Closes #721
=> fix: alter table by changing primary key to be id and add unique contsraint per 721

.github/labeler.yml, .gitignore, Makefile, backend/seeder/main.go, backend/src/handlers/proxy_handler.go, backend/src/handlers/server.go, config/zims.sh, docker-compose.yml
Allows us to develop against local kiwix containers, auto downloads a few zims so search and such can be tested locally
=> feat: add local kiwix dev environment

provider-middleware/video_dl.go
if a video was added that was part of a playlist, we were accidentally storing the ID fo the playlist. causing conflicts
=> fix: video downloads from playlists duplicated external_ids

backend/src/database/helpful_links.go, backend/src/database/open_content.go, backend/src/database/videos.go, backend/src/handlers/open_content_handler.go, backend/src/handlers/open_content_handler_test.go, backend/src/handlers/server.go, frontend/src/Components/inputs/LibrarySearchBar.tsx, frontend/src/Components/inputs/SearchBar.tsx, frontend/src/Pages/Favorites.tsx, frontend/src/Pages/HelpfulLinks.tsx, frontend/src/Pages/HelpfulLinksManagement.tsx, frontend/src/common.ts
Fixes the issue with capitalization in the Helpful Links, and Videos. You can now search with capitalized words and or non-capitalized words, capitalization is irrelevant. Also adds missing search and order by for the student side of helpful links, and favorites. 
- **Related issues**: Closes #713  Closes #712
=> fix: fix search capitalization issues

provider-middleware/video_dl.go
this was starting 1 goroutine per video that needed the thumbnail downloaded, which was in turn calling `fork` and spawning a child process. which was then overloading the server when all 100+ videos needed to be downloaded :man_facepalming:
=> fix: make video metadata sync synchronous to prevent overload 

provider-middleware/video_dl.go
no more of that. anything that is forking is sync
=> fix: make all video operations syncronous

backend/src/database/activity.go, backend/src/models/course.go, frontend/src/Pages/AdminLayer2.tsx, frontend/src/common.ts
Address inconsistencies in calculations and formulas on the Learning Insights Dashboard
Related issues
https://github.com/UnlockedLabs/UnlockEdv2/issues/671
related to https://github.com/UnlockedLabs/UnlockEdv2/issues/530
=> refactor: total activity time query

provider-middleware/video_dl.go
the error with fetching the thumbnails during the pilot was due to spawning child processes when we just need to fetch the thumbnail. 
we can get the info with the google api instead with one request, as we were before.
=> fix: use google cloud api key to fetch youtube metadata

backend/migrations/00036_add_facility_visibility_statuses.sql, backend/seeder/main.go, backend/src/database/DB.go, backend/src/database/libraries.go, backend/src/database/open_content.go, backend/src/handlers/libraries_handler.go, backend/src/handlers/middleware.go, backend/src/handlers/open_content_activity_handler.go, backend/src/handlers/open_content_activity_handler_test.go, backend/src/handlers/open_content_handler.go, backend/src/handlers/open_content_handler_test.go, backend/src/handlers/test_data/libraries.json, backend/src/models/library.go, provider-middleware/kiwix_data.go
Modified the library visibility functionality to be toggled on a per facility basis rather than globally. The changes include:
- Created a new table (facility_visibility_statuses) to manage library visibility per facility.  
- Removed the visibility_status column from the libraries table.  
- Added a new struct with gorm mapping to the new table.  
- Updated SQL queries to reflect the new visibility logic  
- **Related issues**:  Closes #718
---
- https://app.asana.com/0/0/1209485070836358
=> feat: modify library visibility to be per facility according to ticket #718

frontend/src/Components/EnrolledCourseCard.tsx, frontend/src/Components/ProgramCard.tsx, frontend/src/Components/ProgramOutcomes.tsx, frontend/src/Components/ProgressBar.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/Routes/Programs.tsx
This is the initial rough draft of the Program Overview Dashboard, currently all data except for the Name of the Program and the Description is just testing data. 
- **Related issues**: Closes #764 
This is 90% test data, the only actual backend call being made is for the Program, there is **work** that needs to be done in the backend to have and or retrieve the information being represented here. 
---
- https://app.asana.com/0/0/1209485070839503
=> feat: add program overview dashboard with test data

backend/src/database/helpful_links.go, backend/src/database/open_content.go, backend/src/handlers/helpful_links_handler.go, backend/src/handlers/open_content_handler_test.go, backend/src/models/resource.go, frontend/src/Pages/Favorites.tsx, frontend/src/Pages/HelpfulLinks.tsx, frontend/src/Pages/HelpfulLinksManagement.tsx, frontend/src/common.ts
Implemented logic to modify the Helpful link management so that helpful links are no longer system-wide but rather defined at the level of a facility. 
Modified SQL queries to account for helpful links being managed at the facility level.
- **Related issues**: Link to Asana ticket: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209485070836361?focus=true
=> feat: modify helpful link management so helpful links are managed and defined at facility level

frontend/src/Components/Navbar.tsx, frontend/src/Pages/AdminManagement.tsx, frontend/src/Pages/LibraryViewer.tsx, frontend/src/Routes/Programs.tsx, frontend/src/app.tsx
This pr fixes the duplicate icons on the admin management page, removes programs from the navbar for residents, and changes the nested library favorite modal from "Favorite Library" to "Favorite Page" 
- **Related issues**: None in Asana
---
- https://app.asana.com/0/0/1209657740113590
=> fix: fix bug on admin management remove program for residents

backend/src/database/users.go, backend/src/handlers/login_flow.go, frontend/package.json, frontend/src/Components/LibraryCard.tsx, frontend/src/Components/LibraryLayout.tsx, frontend/src/Components/Navbar.tsx, frontend/src/Components/Tour.tsx, frontend/src/Components/UnlockEdTour.tsx, frontend/src/Components/forms/ChangePasswordForm.tsx, frontend/src/Components/forms/LoginForm.tsx, frontend/src/Components/modals/FormModal.tsx, frontend/src/Context/TourContext.tsx, frontend/src/Layouts/AuthenticatedLayout.tsx, frontend/src/Pages/HelpCenter.tsx, frontend/src/Pages/LibraryViewer.tsx, frontend/src/Pages/OpenContent.tsx, frontend/src/Pages/ResidentHome.tsx, frontend/src/Routes/Routes.tsx, frontend/src/common.ts, frontend/src/main.tsx, frontend/yarn.lock
Adds welcome tour to platform. Right now, the temporary button is on the top left corner on the Navbar, where it says "Start Tour". Make sure you are on the home page to start it (working on the fix for this now). Leaving this as a draft for now so I can receive feedback as I make small changes to ui/some phrasing/fix some small bugs here and there. There shouldn't be any major changes.
The start button will be moved to the "get help" section which rich is working on, which is why it has a temporary spot at the moment. I am also still implementing it starting on first log in.
PS- I know that on the second to last tooltip it focuses weird, that is one of the bugs I am trying to fix :)
- **Related issues**: Closes asana task https://app.asana.com/1/1201607307149189/project/1209460078641109/t …
=> feat: add welcome tour

backend/src/handlers/libraries_handler.go
Added logging for capturing user search terms and categories selected.
- **Related issues**: Link to Asana ticket: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209525826202877?focus=true
=> feat: add logging for search terms and categories selected by user

backend/migrations/00040_alter_programs.sql
Added SQL migration for program features development.
=> feat: add sql migrations for program features development

backend/migrations/00041_add_remove_program_columns.sql, backend/seeder/main.go, backend/src/database/section_events.go, backend/src/database/seed_data.go, backend/src/handlers/programs_handler.go, backend/src/handlers/programs_handler_test.go, backend/src/handlers/section_events_test.go, backend/src/handlers/sections_handler_test.go, backend/src/models/calendar.go, backend/src/models/program.go, backend/src/models/program_sections.go, backend/src/models/section_event.go
Made changes to fix seeder and go tests due to migration changes.
=> fix: modify structs and seeder to conform to program database structure

frontend/src/Components/cards/OpenContentCard.tsx
This PR changes the Helpful Link Card navigation on the ResidentHome page so that it properly navigates the helpful link, and creates the activity. 
- **Related issues**: closes id_84
---
- https://app.asana.com/0/0/1209700783671645
=> fix: fix resident home sidebar helpful link navigation

backend/seeder/main.go, backend/src/database/program_sections.go, backend/src/handlers/programs_handler.go, backend/src/handlers/sections_handler.go, backend/src/handlers/sections_handler_test.go, backend/src/models/program_sections.go, frontend/src/Components/PageNav.tsx, frontend/src/Components/inputs/CancelButton.tsx, frontend/src/Components/inputs/DateInput.tsx, frontend/src/Components/inputs/DurationInput.tsx, frontend/src/Components/inputs/NumberInput.tsx, frontend/src/Components/inputs/index.ts, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/Pages/SectionManagementForm.tsx, frontend/src/Routes/Programs.tsx, frontend/src/common.ts
NOTE: Please before testing this change to run `make reset`  and then run the seeder.
Added functionality for allowing administrators to create program sections for a selected program. This change required SQL to be created, backend api changes, and several frontend changes such as creating date, number, duration, and reset button form components. 
- **Related issues**: Link to Asana task: https://app.asana.com/0/1209460078641109/1209485911445028/f.
=> feat: add functionality to create and schedule new section for facility admin per ticket id 47

frontend/src/Pages/CreateProgram.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx
change success text to: "Program created successfully" and fix brief error on loading 
- **Related issues**:
https://github.com/user-attachments/assets/029acb3b-33fb-4ce4-84da-998363a09a11
https://github.com/user-attachments/assets/45c8c7a6-fea2-4602-9f0a-bc618c499ddb
---
- https://app.asana.com/0/0/1209876762905727
- https://app.asana.com/0/0/1209855394721676
=> Fix success text

frontend/src/Components/FavoriteCard.tsx, frontend/src/Components/LibraryCard.tsx, frontend/src/Components/LibraryLayout.tsx, frontend/src/Components/VideoCard.tsx, frontend/src/Components/VideoContent.tsx, frontend/src/Components/VisibleHiddenToggle.tsx, frontend/src/Components/cards/HelpfulLinkCard.tsx, frontend/src/Hooks/sessionView.tsx, frontend/src/Pages/Favorites.tsx, frontend/src/Pages/HelpfulLinks.tsx, frontend/src/Pages/HelpfulLinksManagement.tsx, frontend/src/Pages/ProgramManagement.tsx, frontend/src/Pages/VideoManagement.tsx
-  ## Description of the change
This PR: 
- Adds a list view to all knowledge center views
- Uses session storage to maintain preferred view type 
- **Related issues**: Closes ID 16 in Asana 
If someone recommends we change the list view across favorites, or videos, or anything i won't say i necessarily disagree, as I said, this is a list view based off of the same format as our Program list view.  
https://app.asana.com/0/1209460078641109/1209478696323291/f
=> feat: add list view to knowledge center components

backend/src/database/users.go
Added where clause to GetNonEnrolledResidents func
---
- https://app.asana.com/0/0/1209876778899398
=> fix: added where clause to class enrollments query

backend/src/database/program_classes.go, backend/src/handlers/classes_handler.go, backend/src/handlers/classes_handler_test.go, backend/src/models/program_classes.go, frontend/src/Components/EventCalendar.tsx, frontend/src/Components/PageNav.tsx, frontend/src/Components/TitleManager.tsx, frontend/src/Components/inputs/DateInput.tsx, frontend/src/Components/inputs/RRuleControl.tsx, frontend/src/Components/modals/ModifyClassModal.tsx, frontend/src/Layouts/AuthenticatedLayout.tsx, frontend/src/Pages/ClassManagementForm.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/Routes/Programs.tsx, frontend/src/common.ts, frontend/src/routeLoaders.ts
Added the functionality to modify class section details. This change included some html, javascript, and backend golang coding modifications and additions. 
NOTE: Scheduling section is currently disabled for edit.
- **Related issues**: Link to Asana task: https://app.asana.com/0/1209460078641109/1209485911445029/f
[example.webm](https://github.com/user-attachments/assets/0da2b80e-9400-48db-82d2-b45a8d751393)
=> feat: add functionality so facility admin can edit an existing section per ticket 48

backend/src/database/users.go, frontend/src/Components/VideoContent.tsx, frontend/src/Components/inputs/LibrarySearchBar.tsx, frontend/src/Pages/AddClassEnrollments.tsx, frontend/src/Pages/AdminManagement.tsx, frontend/src/Pages/Favorites.tsx, frontend/src/Pages/ProgramClassEnrollment.tsx, frontend/src/Pages/StudentManagement.tsx
This PR allows you to do a full name search when enrolling a resident into a class 
- **Related issues**: Closes Asana 143
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209941920235491?focus=true
=> fix: fix full name search when enrolling users

backend/src/database/users.go, backend/src/handlers/facilities_handler.go, frontend/src/Components/PageNav.tsx, frontend/src/Pages/AddClassEnrollments.tsx, frontend/src/Pages/ClassEnrollmentDetails.tsx, frontend/src/Pages/ClassManagementForm.tsx, frontend/src/Pages/LibraryViewer.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/Pages/ResidentProfile.tsx, frontend/src/Routes/App.tsx, frontend/src/Routes/Programs.tsx, frontend/src/common.ts, frontend/src/main.tsx, frontend/src/routeLoaders.ts
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209925037018719
when user navigates to an improper page it will return a proper 404 page instead of no data. Also fixes facility switching and user search
=> 404 redirects, fix search with spaces, fix facility switching

frontend/src/Components/modals/AddUserModal.tsx
added error logic to submit handler
https://github.com/user-attachments/assets/e90771a2-a9ec-4b55-a883-62e2fa698cd5
---
- https://app.asana.com/0/0/1209977328642898
=> invalid character weird UX behavior - Fix

frontend/src/Components/LibrarySearchResultsModal.tsx, frontend/src/routeLoaders.ts
Added sort to array.
---
- https://app.asana.com/0/0/1209924956055675
=> Added sort to Search Modal dropdown

frontend/src/Components/inputs/RRuleControl.tsx
Modified labels on the create class form.
- Capitalized 'e' in every.
- Updated the size used for labels: day(s), week(s), and month(s)
If alignment needs to be adjusted further please let me know.
- **Related issues**: Link to Asana ticket [Labels on Create Class form](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209894778875039?focus=true)
=> fix: modify labels on create class form per ticket 128

backend/src/database/users.go, backend/src/handlers/user_handler.go, backend/src/models/program_classes.go, backend/src/models/users.go, frontend/src/Components/ResidentPrograms.tsx, frontend/src/Components/UserPrograms.tsx, frontend/src/Pages/ResidentProfile.tsx, frontend/src/common.ts
This PR does: 
- adds resident programs and their attendance % to the Resident Profile 
- **Related issues**: Asana ...everytime I post a number it just adds some random Asana ticket that's not related..so...idk. 
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209962528167587?focus=true
=> feat: add user programs to resident profile 

frontend/src/Pages/CreateProgram.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx
This PR: 
- changes the color of the cancel button on create program 
- fixes the text on archive class to be plural when necessary 
- **Related issues**: closes asana 124 and 118 
asana - 
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209876762905741?focus=true 
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209876762905722?focus=true
The cancel button in the modal when archiving a class didn't do anything, it just console logged "closing the modal" so I just fixed that little bug, which im assuming was a bug..or well...someone just forgot to add the onClose. So, ya, that too. 
---
- https://app.asana.com/0/0/1209876762905735
=> fix: fix archiving text cancel button color

backend/src/database/programs.go, frontend/src/Pages/ProgramOverviewDashboard.tsx
Disable the Add Class button for Facilities where a Program isn't Offered
https://github.com/user-attachments/assets/8c2b6a1d-b63e-41e4-a91a-b6f92cb4b9c3
---
- https://app.asana.com/0/0/1209962528167593
=> Disable add class button

backend/src/database/users.go
fixes small bug with last PR where operational insights page was broken
=> fix: operational insights filter by role = student

frontend/src/Components/ClassLayout.tsx, frontend/src/Components/ClassStatus.tsx
Added code so that when a class's status is set to 'Completed' or 'Cancelled' it cannot be change-able.
- **Related issues**: Link to Asana ticket [Class status should not be change-able after Completed or Canceled](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210072188481728?focus=true)
=> fix: add logic check for class status of completed and cancelled per ticket 167

backend/src/database/class_enrollments.go, backend/src/database/events_attendance.go, backend/src/handlers/class_enrollments.go, backend/src/handlers/classes_handler.go, backend/src/handlers/events_attendance_handler.go, frontend/src/Pages/AddClassEnrollments.tsx, frontend/src/Pages/ClassEnrollmentDetails.tsx, frontend/src/Pages/ClassEvents.tsx, frontend/src/Pages/EventAttendance.tsx, frontend/src/Pages/ProgramClassManagement.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/Routes/Programs.tsx, frontend/src/routeLoaders.ts
Wired in the enrollment and attendance pages within the class overview tabs. This consisted of modifying routes, backend api paths and removing executable icons, buttons. and removing unused id's from backend api (cleanup).
I also fixed two issues:
- Replaced ProviderAccess feature with ProgramAccess feature on attendance API within the backend code
- Corrected query for displaying residents to mark attendance for. Changed from all residents with a status to only residents with the status of 'Enrolled' 
NOTE: The puzzle icon (navigates to the class overview) was left alone until further notice.
- **Related issues**:  
- Link to Asana ticket [Class Overview Tab Functionality](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210072150791622?focus=true)
- Link to Asana …
=> fix: add class overview tab functionality for attendance and enrollments per ticket 166

provider-middleware/handlers.go, provider-middleware/video_dl.go
This PR changes the middleware to prefer writing to disk instead of assuming we have s3 access, which is preferred because aws's `mounts3` is great and each pod will have a PVC for a subdirectory of the main bucket.
We can still use presigned URL's in the mean-time for serving videos, but eventually will probably have the same s3 directory mounted to nginx to serve them and then we can setup a local cache for content at the deployments.
=> Prepare middleware for offline deployments

backend/src/database/DB.go, backend/src/handlers/programs_handler.go, backend/src/handlers/user_handler.go, backend/src/models/users.go, frontend/src/Components/modals/index.ts
This allows hyphens in first and last names, and updates validation logic for those two struct fields for our users model. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209977398530311?focus=true
=> fix: fix hyphenated name validation

config/kiwix.sh
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210072150791630
=> feat: add script to add kiwix libraries to dedicated instance

backend/seeder/main.go, frontend/src/Routes/Programs.tsx
- Added redirect route to (Programs.tsx) for program-classes/:id to be program-classes/:id/dashboard.
- **Related issues**: Link to Asana ticket [Redirect users from program-classes/:id to program-classes/:id/dashboard](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210136475207630?focus=true)
=> fix: add redirect route for when route is program-classes/:id per ticket 189

backend/src/handlers/server.go, frontend/src/Pages/ResidentProfile.tsx
Added css class name to fix the transfer resident button shifting issue.
- **Related issues**: Link to Asana ticket [Delete Resident and Transfer Resident buttons shifting on click](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210022616266291?focus=true)
=> fix: add css to fix transfer resident button shift on click per ticket id 160

backend/src/database/users.go, backend/src/handlers/login_flow.go, backend/src/handlers/user_handler_test.go
Fix login issue described in slack
=> check for existing user when loggging in to prevent ident mismatch

backend/src/database/class_enrollments.go, backend/src/database/events_attendance.go, backend/src/database/users.go, backend/src/models/resource.go, frontend/src/Components/ClassEnrollmentDetailsTable.tsx, frontend/src/Components/VideoContent.tsx, frontend/src/Components/inputs/DropdownControl.tsx, frontend/src/Pages/AddClassEnrollments.tsx, frontend/src/Pages/AdminManagement.tsx, frontend/src/Pages/ClassEnrollmentDetails.tsx, frontend/src/Pages/CourseCatalog.tsx, frontend/src/Pages/EventAttendance.tsx, frontend/src/Pages/Favorites.tsx, frontend/src/Pages/HelpfulLinks.tsx, frontend/src/Pages/HelpfulLinksManagement.tsx, frontend/src/Pages/MyCourses.tsx, frontend/src/Pages/MyProgress.tsx, frontend/src/Pages/ProgramClassEnrollment.tsx, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/Pages/StudentManagement.tsx, frontend/src/Pages/VideoManagement.tsx, frontend/src/common.ts
Modified dropdowns to be consistent for sorting resident names per ticket 139.
- **Related issues**: Link to Asana ticket is [Standardize on sorting fields for pages with Resident names](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209940257724121?focus=true)
=> fix: modify dropdowns to be consistent for sorting resident names per ticket 139

backend/src/models/jobs.go, backend/tasks/scheduler.go
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210225822622855
=> fix: nil map check in scheduler prevent crash on general tasks

backend/src/database/users.go, backend/src/handlers/dashboard.go, frontend/src/Components/OperationalInsightsCharts.tsx, frontend/src/Pages/OperationalInsights.tsx, frontend/src/Routes/App.tsx, frontend/src/common.ts, provider-middleware/video_dl.go
PR apparently did not merge the first time...
=> operational insights fix (again)

frontend/src/Pages/ProgramManagement.tsx
Remove categories from program 
- **Related issues**: Asana 206
- 
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210129036130426?focus=true
---
- https://app.asana.com/0/0/1210225822622838
=> fix: remove categories dropdown

frontend/src/Pages/AdminManagement.tsx
Updates the button on the admin management to inform user creating new admin what type of admin will be created 
- **Related issues**: Asana id 188
=> fix: update add user in admin management

frontend/src/Pages/ProgramManagement.tsx
renames num of classes to total classes on programs management dashboard
---
- https://app.asana.com/0/0/1210241045383743
=> fix: rename # of Classes to total classes

backend/src/database/class_events.go, backend/src/handlers/class_events.go, backend/src/handlers/events_attendance_handler.go, backend/src/handlers/user_handler.go, backend/src/handlers/utils.go, backend/src/models/class_event.go, frontend/src/Components/ClassLayout.tsx, frontend/src/Components/cards/ActivityHistoryRowCard.tsx, frontend/src/Components/helperFunctions/formatting.tsx, frontend/src/Components/helperFunctions/index.ts, frontend/src/Components/inputs/RRuleControl.tsx, frontend/src/Components/inputs/TimeInput.tsx, frontend/src/Components/inputs/index.ts, frontend/src/Components/modals/CancelClassEventModal.tsx, frontend/src/Components/modals/FormModal.tsx, frontend/src/Components/modals/RescheduleClassEventModal.tsx, frontend/src/Components/modals/index.ts, frontend/src/Pages/ClassManagementForm.tsx, frontend/src/Pages/Schedule.tsx, frontend/src/common.ts
- Added the functionality for allowing an administrator to reschedule a single event from a facility schedule. 
- Modified/Added logic within the backend API
- Modified/Added logic within the frontend API
DEPENDENT ON PR #881 & #882
NOTES
- For development/testing purposes I have "Temporarily" added the Edits Action modal to the View Calendar button on the Class Edit screen (ClassManagementForm.tsx).  See Screen shot below.
- **The changes for this PR are located within this COMMIT:** [feat: add functionality to reschedule single event from facility schedule](https://github.com/UnlockedLabs/UnlockEdv2/commit/b8a3acfc760211edecf7989148abbf91b0d12c47)
- **Related issues**: Link to Asana tickets [Reschedule Single Event from Facility …
=> feat: add functionality to reschedule single event from facility schedule per ticket 205

frontend/src/Pages/ProgramManagementForm.tsx
Adjusted spacing between cards and removed indent of the form on Edit Program page
---
- https://app.asana.com/0/0/1210356415337034
=> Edit Program UI adjust

backend/src/database/users.go, backend/src/handlers/user_handler.go, backend/src/models/users.go, frontend/src/Components/TransferSummaryPanel.tsx, frontend/src/common.ts
Included the name of the program that the class is a part of (bc it may not always match the class name).
- **Related issues**: 
[Ticket id: 268](https://app.asana.com/1/1201607307149189/project/1209457756469406/task/1210272664885981?focus=true)
=> Add Program name to TransferSummaryPanel text.

backend/src/handlers/facilities_handler.go
Change admin route so department admin facility switcher works. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210487096611574?focus=true
=> fix: switch route to dept admin

backend/src/database/programs.go, backend/src/handlers/programs_handler.go, backend/src/models/program.go, frontend/src/Pages/ProgramOverviewDashboard.tsx, frontend/src/common.ts
Added Active Residents card to the Program Overview Dashboard screen. This consisted of adding a scalar to the SQL query along with modifying CSS and HTML. 
- **Related issues**: Link to Asana ticket [Change "Residents" to "Enrollments for "Active Enrollments" on Program Overview Dashboard](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210481100839392?focus=true)
=> feat: add active residents card to program overview dashboard per ticket 287

backend/migrations/00051_add_enrolled_on_dt_to_completion.sql, backend/src/database/class_enrollments.go, backend/src/models/program_classes.go, frontend/src/Components/modals/CompletionDetailsModal.tsx, frontend/src/Pages/ClassEnrollmentDetails.tsx, frontend/src/common.ts
Updates the Completion details modal with new verbage, and includes a check that guarantees that the date shown is either 1. The start date of the class if the user was enrolled prior to class tart 2. The date the user was enrolled if enrolled post start of the class
Outside of that, there was a couple bugs due to changeStatusValue not being set in time for renders and PATCH calls. Prior to this you were unable to bulk update or singularly update "Completed" status due to this issue. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210481100839405?focus=true
=> fix: update completion details modal 

frontend/src/Pages/ResidentProfile.tsx
Restored logic to allow accounts to be deleted from the Resident Profile page 
https://github.com/user-attachments/assets/9246d5f2-1b8c-416c-bc2d-7c618b71d55a
---
- https://app.asana.com/0/0/1210487096611556
=> Add delete resident logic back to residentProfile page

provider-middleware/daily_program_history.go, provider-middleware/handlers.go
some fixes I had added on a PR that I closed that were still needed
=> small fixes: context and cancellation inside middleware

backend/src/database/program_classes.go, frontend/src/Pages/ClassManagementForm.tsx
Removed all scheduling-related logic from the ClassManagementForm, while preserving support for editing and saving the room field 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209465647700741/task/1210495081491628?focus=true
https://github.com/user-attachments/assets/420327ad-812d-441f-ade7-8c9d8063a516
=> Remove "Scheduling" section from Edit Class page

backend/src/database/class_events.go, backend/src/database/programs.go, backend/src/handlers/class_events.go, backend/src/handlers/events_attendance_handler.go, backend/src/handlers/programs_handler.go, backend/src/handlers/utils.go, backend/src/models/program.go, frontend/src/Pages/ClassEvents.tsx, frontend/src/Pages/EventAttendance.tsx, frontend/src/Pages/ProgramManagement.tsx, frontend/src/api/api.ts
This allows facility admins and department admins to export program data to CSV. 
Also fixes a couple random little bugs around attendance and dates.
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210454753698729?focus=true
The data I had to work with was pretty trash, so don't take the column data in the screenshots to heart, test it yourself please. A lot of it is from the seeded data and me working around not having any historical classes to add attendance to, etc.
=> feat: export program data to csv

frontend/src/Components/modals/RescheduleClassEventSeriesModal.tsx
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210608462768447
If any core features or components were removed with this PR, please note them here so that they can be added to the wiki (see [Deprecated features and Components](https://github.com/UnlockedLabs/UnlockEdv2/wiki/Deprecated-Features-and-Components)).
=> feat: update the button text on the edit series (recurring) modal to say "Save Changes"

frontend/src/Pages/EventAttendance.tsx
Changed text from "Back" to "Cancel"
https://app.asana.com/1/1201607307149189/project/1210319608132195/task/1210608462768451
Not sure if this is the correct way to push on an old PR
If any core features or components were removed with this PR, please note them here so that they can be added to the wiki (see [Deprecated features and Components](https://github.com/UnlockedLabs/UnlockEdv2/wiki/Deprecated-Features-and-Components)).
=> feat: updated text on event button from 'back' to 'cancel'

backend/src/database/class_events.go, backend/src/handlers/class_events.go, backend/src/models/calendar.go, frontend/src/Components/ClassEventDetailsCard.tsx, frontend/src/Components/ClassInformationDetailsCard.tsx, frontend/src/Components/ResidentPrograms.tsx, frontend/src/Pages/ResidentOverview.tsx, frontend/src/Pages/Schedule.tsx, frontend/src/common.ts
Added Calendar and Resident Programs tables to the Resident Programs UI
https://github.com/user-attachments/assets/d0693deb-f4c4-4f7a-912f-1ba16f53d268
---
- https://app.asana.com/0/0/1210605185296653
=> Update Resident Programs UI

backend/src/database/users.go, backend/src/models/calendar.go, backend/src/models/users.go, frontend/src/Components/ResidentPrograms.tsx, frontend/src/common.ts
Added tooltip and icon to Resident Programs page.
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210383025477741
https://github.com/user-attachments/assets/e2bc0023-a3fc-4fa6-adae-74221e65b0c0
=> Add tooltip and icon to Resident Programs page 

frontend/src/Pages/AdminManagement.tsx
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210495081491646
* Please be aware that my format extension "formatted" the comments within the provider-service-yaml file.
=> feat: adjusted alignment for super admin add buttons

backend/src/database/programs.go, backend/src/models/program.go
PR adds instructor name to csv export 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210723359034018?focus=true
=> fix: add instructor name to csv export

frontend/src/Components/ResidentPrograms.tsx
Few small fixes in relation to the recently merged in PR that handles change reason displaying on info icon. Handles for all scenarios where there is a change reason, not strictly the “Incomplete: Failed to Complete”. 
- **Related issues**: PR #948 and asana ticket [ID-270](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210383025477741?focus=true)
=> fix: uses ULIcomponent and adds icon for all instances of change reason

frontend/src/Components/PageNav.tsx
(https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210707681181866)
[Video walk through of process.
](https://drive.google.com/file/d/1tYKwXQmDYBEZxVb9amiPnKiutvkOZHJ5/view?usp=sharing)
If any core features or components were removed with this PR, please note them here so that they can be added to the wiki (see [Deprecated features and Components](https://github.com/UnlockedLabs/UnlockEdv2/wiki/Deprecated-Features-and-Components)).
=> fix: modified PageNav component to reset pagination issue

backend/migrations/00053_add_deactivated_column_users.sql, backend/src/database/users.go, backend/src/handlers/auth.go, backend/src/handlers/class_enrollments.go, backend/src/handlers/login_flow.go, backend/src/handlers/user_handler.go, backend/src/handlers/utils.go, backend/src/models/resource.go, backend/src/models/users.go, frontend/src/Components/UserActionsDropdown.tsx, frontend/src/Components/cards/ActivityHistoryRowCard.tsx, frontend/src/Components/forms/LoginForm.tsx, frontend/src/Components/modals/DeactivateUserModal.tsx, frontend/src/Components/modals/index.ts, frontend/src/Pages/ResidentProfile.tsx, frontend/src/Pages/StudentManagement.tsx, frontend/src/common.ts, frontend/src/useAuth.ts
This PR opens up the ability for administrators to deactivate a user. With this feature, these requirements have been met. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210176909290537?focus=true
=> feat: add ability to deactivate user

frontend/src/Layouts/AuthenticatedLayout.tsx, frontend/src/Pages/LibraryViewer.tsx, frontend/src/css/app.css
This PR makes sure that we don't get odd double scroll behavior, particularly in the library viewer and iFrame. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210825285656050?focus=true
https://www.loom.com/share/dbc165b247d04fc2af1177e5006d673f?sid=71c87262-6994-4b2d-b3f0-013bad32c2e2
=> fix: single scrollbar in library viewer

backend/src/database/program_classes.go, backend/src/models/program_classes.go, frontend/src/Components/inputs/DateInput.tsx, frontend/src/Pages/ClassEvents.tsx, frontend/src/Pages/ResidentProfile.tsx, frontend/src/common.ts
Attendance date is in the future -  Label (muted text + Available after MM/DD)
Attendance date is in present/past and class active - Clipboard w/check mark icon + "Mark attendance" (on hover, underline)
Class is cancelled or completed - Eye icon + "View attendance" (on hover, underline)
**Related vidz or screenshot: 
https://github.com/user-attachments/assets/d9d6aa8b-991e-4430-8aaf-bf4c6c046213
---
- https://app.asana.com/0/0/1210251192355414
=> Replace the Mark Attendance button button on Attendance page for dates in the future

backend/src/database/class_enrollments.go, backend/src/models/program.go, backend/src/models/program_classes.go, backend/tests/integration/classes_test.go, frontend/src/Components/modals/ModifyClassModal.tsx
* Added test  runUpdateActiveClassToCompletedTest
* Added logic to update model.ProgramCompletions when Class status has been updated to completed
* Updated ModifyClassModal to explain impact
- **Related issues**: [Link to related Asana ticket that this closes.](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210883654707924)
Please include additional context or information that the reviewer needs to understand the PR. This includes:
- Known issues that the PR does not address
- What areas to focus on
- What decisions were considered and decided against.
If any core features or components were removed with this PR, please note them here so that they can be added to the wiki (see [Deprecated features and Components](https://github.com/UnlockedLabs/UnlockEdv2/wiki/Dep …
=> Bug & UX Fix: Updating class status should explain impact and correctly log completions

backend/migrations/00056_add_page_feature_flags_table.sql, backend/migrations/00057_insert_page_feature_flags.sql, backend/src/database/feature_access.go, backend/src/handlers/feature_access.go, backend/src/handlers/helpful_links_handler.go, backend/src/handlers/open_content_handler.go, backend/src/handlers/video_handler.go, backend/src/models/feature_flags.go, frontend/src/Components/FeatureLevelCheckboxes.tsx, frontend/src/Components/Navbar.tsx, frontend/src/Components/inputs/CheckboxGeneric.tsx, frontend/src/Pages/OpenContent.tsx, frontend/src/Pages/VideoManagement.tsx, frontend/src/common.ts
Added page level feature toggling as sub-features under the main feature toggles. Specifically, this adds support for Request Content, Helpful Links, and Upload Video as sub-features under the Knowledge Base feature.
Key changes:
- Added a new database migration that: 
- Creates a page_feature_flags table. (This will be dropped on goose down)
- Adds three additional enums to the Feature type. (This will be kept on goose down since this is an enum, unless required to remove)
- Inserts initial values for the page feature flags (defaulted to true).
- Created a handler for toggling page level features. This keeps the code base clean and avoids bloating the existing feature toggle logic with nested sub-feature handling.
- Updated the frontend to introduce a parent to child checkbox …
=> feat: add logic to allow ability to toggle three specific page level features per ticket 377

frontend/src/Components/dashboard/TopContentList.tsx
added a tooltip to the "Your Top Content" that says, "Based on what you’ve viewed most. This list updates as you use UnlockEd more."
- **Related issues**: [Asana Task](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210903016486445?focus=true)
If the PR includes changes to the UI: 
- Please add screenshots or a short screengrab of the change 
- Include images at 1366 x 768 resolution for any Resident-facing changes.
=> Add descriptive tooltip -> Your Top Content
