.husky/check_unstaged.py
.husky/pre-commit
README.md
database/seeders/DefaultAdmin.php

Adds ANSI-colored string warning if there are unstaged files in the CWD that prettier may have formatted, and will not be committed in your git commit.
The alternative would be to have `git add .` run in this hook, but we cannot arbitrarily do that because someone may have selectively committed

Feature: add git hook to check for unstaged files that prettier may have written to during commit hook

---

.github/cliff.toml
.github/workflows/ci.yml
.github/workflows/oxlint.yml
.github/workflows/prettier.yml
.husky/pre-commit
.prettierignore
resources/js/Pages/Welcome.tsx
workflow.md

I would like to move each major CI step to its own action, this will help in the long run to quickly determine which one failed. Because we are working with linters, formatters, testers, steps for commit changes, changelogs, I think its best to at the very least separate them out to their own category.

move linter to its own action, add documentation about commit messages

---

.github/cliff.toml
.github/workflows/oxlint.yml
.github/workflows/prettier.yml
.husky/pre-commit
package.json
workflow.md

Currently we have `Prettier` running as a formatter but as the front end code grows, we will need something like `eslint` which is well known for being slow and __not__ written in Rust.  So the clear option is `oxlint` which is neither

feat: add oxlint linting system for frontend code to githook and add github action

---

app/Services/CanvasServices.php

SELF kept getting auto corrected to `self` and there was absolutely no need for the base and api URL's to be saved, idk what i was smoking but that was absolutely pointless and just made everything super convoluted and confusing, and i just noticed that my last PR fix had made the base url hold the api uri anyway, so it would have legit broke everything

fix: correct mistake in unneeded api_url

---

README.md
app/Console/Commands/MakeControllerTest.php
app/Http/Controllers/v1/EnrollmentController.php
app/Http/Requests/StoreEnrollmentRequest.php
app/Http/Requests/UpdateEnrollmentRequest.php
database/factories/EnrollmentFactory.php
tests/Feature/EnrollmentControllerTest.php

This provides a new command: `artisan app:make-controller-test {NameOfController}`
That will prompt the user for information about the controller, model, and visitbility and generate a class of tests that will test for all the basic CRUD operations and assert that either the route is protected (will fail if non-admin makes requests) or it will assert that the user will be returned only data that belongs to the user.

feat: add controller test generation command rough draft

---

resources/js/Pages/Welcome.tsx

Issue proof:
After I built and ran, I noticed that the login button was not visible in light mode, so I changed the text color of the login button to primary.
Here is what it looks like in light mode:
And how it looks in dark mode:

fix: make login button visible

---

app/Http/Controllers/v1/Actions/StoreCanvasCoursesController.php
app/Http/Controllers/v1/Actions/StoreUserCourseController.php

Corrected the key names for course `description` and course img_url to match those in Canvas and v2 database. Replaced the nullish coalescing operators with else statements to stop description and img_url values from being repeated from previous course during course iteration process.

fix: change course description and image array key names to match Canvas

---

resources/js/Pages/Users.tsx

This resolves issue #127. Also handles the case where a user is edited then another user is selected afterward.

fix(127): handle properly clearing user form

---

resources/js/Components/forms/EditUserForm.tsx
resources/js/Pages/Users.tsx

Hooks must always be at the top level of react components. My bad on letting this slip during code review.

fix: fixes invalid use of hooks in edit user form

---

resources/js/Pages/Users.tsx

It had thought it was still on page 2 of the search results, even though the search results were all contained on page 1.

fix(176): fix bug in User search

---

app/Http/Controllers/v1/Actions/StoreCanvasCoursesController.php

In order to avoid `TypeError` due to the  `provider_platform_id` in request being a `string` instead of `int`, updated code to use the newer method of generating a provider service.

fix #224: implement `getProviderServices` to get Canvas service

---

frontend/src/Components/forms/ChangePasswordForm.tsx

Adds password UI validation and should close https://github.com/UnlockedLabs/UnlockEdv2/issues/272
Implements following UI changes:
* New password messages when the password does/doesn't meet the minimum length or include one number
* New message when the confirm password doesn't match the new password
* Form submission is blocked if any of the validation rules fail

feat: adds password ui validation

---

.github/workflows/container_builds.yml
.gitignore
backend/src/database/users.go
backend/src/handlers/actions.go
backend/src/handlers/activity_handler.go
backend/src/handlers/auth.go
backend/src/handlers/dashboard.go
backend/src/handlers/facilities_handler.go
backend/src/handlers/left_menu_handler.go
backend/src/handlers/login_flow.go
backend/src/handlers/milestones_handler.go
backend/src/handlers/oidc.go
backend/src/handlers/ory.go
backend/src/handlers/outcomes_handler.go
backend/src/handlers/programs_handler.go
backend/src/handlers/provider_platform_handler.go
backend/src/handlers/provider_user_management.go
backend/src/handlers/provider_user_mapping_handler.go
backend/src/handlers/server.go
backend/src/handlers/upload_handler.go
backend/src/handlers/user_activity_handler.go
backend/src/handlers/user_handler.go
backend/src/service.go
build
docker-compose.yml
frontend/Dockerfile
provider-middleware/README.md
provider-middleware/data.go

This is a WIP.  I think it could be better, and some feedback would be welcome.
In particular I am wavering on logging errors where ORM calls fail.  Either way the error message generated by GORM would be propagated to the handlers.  I'm not sure if I should log every failure in backend/databases/, or cut back on the ones that are there now.  My initial thought is instead of logging a separate entry, instead returning a modified error object that includes both the GORM error message and some information about which action failed, which then gets presented when an error is thrown in the handler.
I'm also interested in hearing in whether I should include more fields in the handlers.  I went pretty lightweight in terms of what data I included, which is both readable and scannable.  There is …

refactor: Make logging more structured and consistent

---

frontend/src/Components/forms/ShowImportedUsers.tsx

Changes the background on import users modal so text is seen in dark mode. Closes #326

fix: fixes import users modal on dark mode

---

backend/src/database/provider_user_mappings.go
backend/tests/test_data/users.json
frontend/src/Components/NewOidcClientNotification.tsx
frontend/src/Components/forms/MapUserForm.tsx
frontend/src/Pages/ProviderUserManagement.tsx

Fixes the user management mapping modal. This updates the UI for more clarity and uses backend pagination rather than doing it in the frontend. It renders different views for when a user is fuzzy matched vs not, clears up naming conventions, and provides the user with more information on what each page means. Functionality should be the same as it was before. Screenshots below for reference:
If the user has no fuzzy matches, will show all users.
If the user has a fuzzy match, it will show that match.
On selection of a user the map student button is enabled.
If they click see all users, it will show all users along with a link to display the fuzzy users again.
Closes #331.

fix: fixes mapping modal, updates pagination, updates seeder

---

backend/src/handlers/actions.go
backend/src/handlers/activity_handler.go
backend/src/handlers/dashboard.go
backend/src/handlers/provider_platform_handler.go
backend/src/handlers/provider_user_mapping_handler.go
backend/tests/facilities_test.go
frontend/src/AuthContext.tsx
frontend/src/Pages/Unauthorized.tsx
frontend/src/app.tsx

When a user is not logged in and tries to access any page that requires authentication, they will be redirected to the login page.
When a student (non-admin) is logged in, and tries to access a page that requires administrative privileges, they will be presented with the following page:
When any logged in user attempts to access a page that doesn't exist, they will be presented with: 
fixes #344

feat: add unauthorized page and protect routes

---

backend/tests/facilities_test.go
frontend/src/Components/Navbar.tsx
frontend/src/Components/PageNav.tsx
frontend/src/Layouts/AuthenticatedLayout.tsx
frontend/src/Pages/CourseCatalog.tsx
frontend/src/Pages/Dashboard.tsx
frontend/src/Pages/MyCourses.tsx
frontend/src/Pages/MyProgress.tsx
frontend/src/Pages/ProviderPlatformManagement.tsx
frontend/src/Pages/ProviderUserManagement.tsx
frontend/src/Pages/ResourcesManagement.tsx
frontend/src/Pages/UserActivity.tsx
frontend/src/Pages/Users.tsx

Duplicate of #353 because that was accidentally closed 🤷‍♂️ 
This PR introduces a pinnable navigation bar.
- On large screens users can "unpin" the navbar by clicking << and "pin" the navbar by clicking >>. 
- They can open a hidden navbar by clicking the hamburger menu.
- On smaller screens the navbar is automatically hidden and cannot be pinned.
- Navbar "pin" settings are saved in localstorage. 
https://github.com/user-attachments/assets/446113e8-dda7-438e-a7d4-90d5163d6037
Other changes that were included in this PR:
- Refactored the PageNav to be part of AuthenticatedLayout.
- Fixed a logging message on `facilities_test` (The linter kept failing on the pre-commit hook.)
Closes #340

feat: add collapsible navigation component

---

frontend/src/Components/CatalogCourseCard.tsx

[Screen Shot 2024-08-23 at 2.23.28 PM.pdf](https://github.com/user-attachments/files/16732979/Screen.Shot.2024-08-23.at.2.23.28.PM.pdf)
[Screen Shot 2024-08-23 at 2.24.03 PM.pdf](https://github.com/user-attachments/files/16732982/Screen.Shot.2024-08-23.at.2.24.03.PM.pdf)

added responsive design to pills

---

backend/migrations/main.go
frontend/src/Components/CategoryItem.tsx
frontend/src/Components/CurrentlyEnrolledClass.tsx
frontend/src/Components/LinkItem.tsx
frontend/src/Components/MilestonesBarChart.tsx
frontend/src/Components/MonthActivityChart.tsx
frontend/src/Components/NotificationCard.tsx
frontend/src/Components/NotificationsSideBar.tsx
frontend/src/Components/ResourcesSideBar.tsx
frontend/src/Components/UserActivityMap.tsx
frontend/src/Components/forms/EditProviderForm.tsx
frontend/src/Components/forms/EditUserForm.tsx
frontend/src/Components/forms/LoginForm.tsx
frontend/src/Components/forms/MapUserForm.tsx
frontend/src/Pages/AdminDashboard.tsx
frontend/src/Pages/MyCourses.tsx
frontend/src/Pages/MyProgress.tsx
frontend/src/Pages/ResourcesManagement.tsx
frontend/src/Pages/StudentDashboard.tsx
frontend/src/api/api.ts
frontend/src/common.ts

Refactor of the any types in the frontend directory 
**Related issues**: #369 
N/A
N/A

Frontend refactoring pt.1

---

frontend/src/Components/forms/LoginForm.tsx

The prev login page had a checkbox with remember me next to it. We didn't have any functionality for that, so it was removed to not confuse the user.
**Related issues**:
Closes #389

Remove-remember-me-button-from-login-page

---

frontend/src/Components/Toast.tsx

Updates toast color so that color changes for success and error. Previously these were grey.
Light mode:
Dark mode:

fix: fixes toast alert colors

---

.github/workflows/project-status-update.yml

This pull request introduces a GitHub Actions workflow that automatically updates the status of associated GitHub Project items to "In Review" when a pull request is created, reopened, or edited. The workflow uses the GitHub API to locate the relevant project item linked to the pull request and modifies its status accordingly.
- **Related issues**: This PR addresses the need for automatic status updates in project management workflows to streamline the review process for new pull requests. No specific issue numbers to close.
No UI changes are included in this pull request, as this change is purely workflow-based.
The workflow is defined in `.github/workflows/project-status-update.yml` and is triggered on the `pull_request` event. It interacts with the GitHub Projects API to locate the …

feat: change status of PR to "In Review" when added to project

---

backend/src/database/libraries.go
backend/src/handlers/libraries_handler.go
backend/src/handlers/libraries_handler_test.go
backend/src/models/library.go
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/Navbar.tsx
frontend/src/Components/TabView.tsx
frontend/src/Components/VisibleHiddenToggle.tsx
frontend/src/Pages/MyCourses.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/OpenContentManagement.tsx
frontend/src/Pages/ProviderPlatformManagement.tsx
frontend/src/app.tsx
frontend/src/common.ts

Adds the open content management UI, and fixes a couple things in the backend for visibility. Also moves toast props to common file for access in other places.
- **Related issues**: Closes #409 
Admin View/Open Content Management:
Student View/Open Content:
There are a few TO DO's I have left in there that are in regards to updating the UI once we have the scraper completed. It is making sure that we have the correct image URL so we can use it-- right now it is hard coded since all libraries are Kiwix. I also would love some feedback on how we should implement different colors for different providers. Should this be a color stored in the database? It will need to be a consideration once we add a new open content provider. 
ALSO: I realize that the images look a little funky now. I am …

Adds open content management ui for admins and students

---

backend/src/handlers/middleware.go
backend/src/handlers/proxy_handler.go
backend/src/handlers/server.go
backend/src/models/open_content.go
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/TabView.tsx
frontend/src/Components/VisibleHiddenToggle.tsx
frontend/src/Pages/LibraryViewer.tsx
frontend/src/api/api.ts
frontend/src/app.tsx
frontend/src/common.ts
provider-middleware/handlers.go
provider-middleware/middleware.go

- adds proxy middleware and handler for forwarding requests to kiwix
- adds ui for library content
- updates the open content ui to display smaller images
- fixes filter on admin open content management that wasn't working properly
- adds pagination onto open content ui
- **Related issues**: Closes #431 
We need to make sure the headers are correct in production environment for the proxying.

feat: add library reverse proxy middleware and handler, update frontend

---

frontend/src/Components/PageNav.tsx

Updates `PageNav.tsx` to not use daisyUI navbar component and instead simply uses `flex` and `justify-between` for styling. Removes unnecessary padding.
- **Related issues**: Closes #426 
I cannot reproduce the original bug, so if someone could check if this fixes the UI that would be great.

fix: remove daisyUI navbar class to fix scrollbar

---

provider-middleware/kolibri_data.go

fix: add exporting struct fields to temp struct

---

frontend/src/Components/forms/EditProviderForm.tsx

Returns access key input to how it was originally before refactor. This was necessary because we need to modify the class so that the text in the input does not overlap the eye icon. I also added a prevent default on mousedown event on the eye icons so the input box does not unfocus (unfocusing made it appear glitchy).
- **Related issues**: Closes #453

fix: remove duplicate access key label

---

backend/src/handlers/auth.go
frontend/src/Components/Navbar.tsx
frontend/src/Components/PageNav.tsx
frontend/src/Layouts/AuthenticatedLayout.tsx
frontend/src/Pages/AdminDashboard.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/app.tsx
frontend/src/routeLoaders.ts

This adds facility context switching on the admin side. It also updates both the admin and student portal to display the current facility in the PageNav component, and moves the dropdown that contains logout and theme toggle to the Navbar component. Also updates the routes to not pass in the facility name in the path as it's not needed anymore. Adds loader to the admin Authentication Layout route to render facilities.
- **Related issues**: Closes #425 
https://github.com/user-attachments/assets/6b315b58-205a-4a68-b0ac-9e7106b4fae7
I want to make sure the UI aligns with what @chrissantillan was looking for.

feat: add facility context switch and ui

---

backend/migrations/00014_make_drop_create_insert_daily_activity.sql
backend/src/database/activity.go
backend/src/database/user_catalogue.go

@PThorpe92 Fixed some SQL queries within the activity.go, user_catelogue.go, and added custom Kolibri logic to the insert_daily_activity function.
activity.go - Added an order by to the monthly activity query (GetAdminDashboardInfo) and changed left joins to inner joins when getting course milestones (GetAdminDashboardInfo). The order of the monthly activity will be by date ascending. The left join on milestones was pulling milestones that did not pertain to what was requested.
user_catelogue.go - Modified GetUserCourses query to pull only the requested user course records by changing left joins within the query.
insert_daily_activity - modified function to handle Kolibri time delta.

SQL Query Fixes

---

frontend/src/Pages/ResourcesManagement.tsx

Updated `activeLinkToDelete` check from a boolean to an explicit undefined check to correctly include the first index.
- **Related issues**: #467 
https://github.com/user-attachments/assets/2406a467-80a2-4787-a6ad-67adbb0df866
The issue in `ResourcesManagement.tsx` is that `activeLinkToDelete` is set to 0 when attempting to delete the first link in a collection. Since 0 is treated as a falsy value in JavaScript, the condition `activeLinkToDelete && deleteLink(collection, activeLinkToDelete)` fails, preventing the deletion of the first link. In this case, replacing the condition with an explicit check for `undefined` (to align with the author's intent) would resolve the issue and allow deletion of the first link.

fix: update condition to check for active link deletion for the first index

---

provider-middleware/kolibri.go

@PThorpe92 Changed inner join on exams_exam to be left outer joins as exams_exam doesn't exist until teacher activates it. Also, added logic for when a teacher adds more lessons/assignments or quizzes to a class after the class has existed for sometime. Basically logic that monitors the total_progress_milestones for kolibri classes to make sure to account for any additional content added by teachers.

Kolibri Logic Enhancement and Fixes

---

backend/seeder/main.go
backend/src/handlers/programs_handler.go
frontend/src/Components/Navbar.tsx
frontend/src/Components/ProgramCard.tsx
frontend/src/Pages/Programs.tsx
frontend/src/app.tsx
frontend/src/common.ts

Added the Programs page, in the Admin view there is a Add Program button, in the User view the Add Program button is removed. Added Course Catalog view for Admin users to view courses. Added program tags in the seeder functions for Programs. 
- **Related issues**: Related to issue #465, Closes #446. 
Admin View Grid 
Admin View List 
User View Grid
User View List 
A base implementation of the Programs Page without the ability to explicitly add or edit a program, if Add Program is clicked the user is prompted that the feature will be implemented soon.

feat: add Programs page and 'tags' to seed data

---

provider-middleware/brightspace.go
provider-middleware/brightspace_data.go

Two methods to import Brightspace users from a CSV file downloaded from the Brightspaces datahub. The GetUsers method downloads the data, imports it into a slice of BrightSpace user models, loops through the slice, serializes the BrightSpace user slice into the UnlockEd ImportUser model type, and then returns a slice of ImportUser. 
- **Related issues**: Part of [#430](https://github.com/UnlockedLabs/UnlockEdv2/issues/430)

feat: add GetUsers, IntoImportUsers in provider-middleware

---

frontend/src/Pages/ResourcesManagement.tsx

This pull request implements functionality for the Resource Management page that enhances the user experience both in rearranging resource cards and modifying text fields. In addition to tracking the initial order of the cards to manage the "Publish Changes" button state, we have also updated the Modify Collections section to monitor text changes. When users edit a resource's name or URL, the "Publish Changes" button is activated to indicate modifications. If the user reverts the text back to its original state, the button will automatically deactivate, ensuring that the UI accurately reflects the state of modifications. This cohesive behavior across both card arrangements and text fields provides users with clear visual feedback on their actions, significantly improving the usability of …

Resource management

---

backend/src/handlers/user_handler.go
frontend/src/Components/forms/AddUserForm.tsx
frontend/src/Components/inputs/TextInput.tsx

**Key Changes Implemented to Support Requirements:**
1. **Pattern Prop Addition:**
- Added a new `pattern` prop to the `TextInput` component to support different validation patterns for different fields.
2. **Validation Pattern Modifications:**
- **First and Last Names:** `^[A-Za-z\s]+$` – allows only letters and spaces.
- **Username:** `^[A-Za-z0-9]+$` – allows only letters and numbers (no spaces).
3. **Updated Error Messages:**
- Replaced the generic error message "First/Last and Username must contain letters and numbers only" with field-specific messages.
- **Username Error:** Now says "Username can only contain letters and numbers."
- **Name Fields:** Show "can only contain letters and spaces."
**Benefits of These Changes:**
- **Allow Spaces in Names:** Users can now include spaces in …

fix: added_frontend_validation

---

backend/migrations/00021_add_open_content_activity_tables.sql
backend/src/database/DB.go
backend/src/database/libraries.go
backend/src/database/open_content.go
backend/src/handlers/libraries_handler.go
backend/src/handlers/middleware.go
backend/src/handlers/proxy_handler.go
backend/src/handlers/server.go
backend/src/handlers/video_handler.go
backend/src/models/library.go
backend/src/models/open_content.go

Added feature to track users (students/admins) viewing activity when interacting with open content (videos and libraries). A couple of details follow:
Two tables were created to track open content library activity.
1. open_content_urls - This table is used as a lookup table for when a user clicks an open content link. If the url that the user requested does not exist then it is created and the ID is used for the saving in the open_content_activities table. This table is used for improving query performance.  
2. open_content_activities - This table is used to track all user open content activity, basically tracks user requests for all open content.

Track open content library activity #490

---

backend/src/database/users.go

Refactored GetCurrentUsers func to account for the count not being correctly calculated and accounted for the Limit(n) not being applied in the proper order in the qry execution.
- **Related issues**: 
Closes: #442 
https://github.com/user-attachments/assets/a55aa99d-1163-4155-8439-e9b6fb6a528f

BUG-FIX: Pager Control Admin and Student Management

---

frontend/src/Components/InternalLink.tsx
frontend/src/Components/StaticContentCard.tsx

The static content card has links that direct internally, using the external link opens it up in another window. This PR gives us an internal link component, and makes the static content card use it

feat: add internal link component, make static content card use it

---

backend/src/database/leftmenulinks.go
backend/src/handlers/left_menu_handler.go
backend/src/handlers/left_menu_handler_test.go

Adds limit to the backend so that resources (aka now helpful links) can be filtered to just the top 5 helpful links.
- **Related issues**: works towards #527 but this will be completed in my other PR (#532)
No relevant screenshots.
Depending on the order that the PRs are merged in, I'll have to modify one of them to update the frontend dashboard to add the limit to the api call in the frontend. This one is probably easier to merge in first and then i can push that new change into #532 and it can be merged in with that.

feat: add limit param for resources

---

frontend/src/Components/FeatureLevelCheckboxes.tsx
frontend/src/Components/Navbar.tsx
frontend/src/Components/ResourcesSideBar.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/OpenContentLevelDashboard.tsx
frontend/src/Pages/OpenContentManagement.tsx
frontend/src/Pages/VideoManagement.tsx
frontend/src/app.tsx
frontend/src/common.ts
frontend/src/useAuth.ts

Renamed the Open Content page to Knowledge Center, updating the following areas:
Side Navigation:
For Admins, display the link as "Knowledge Center Management".
For Residents, display the link as "Knowledge Center".
Breadcrumb Page Title:
Update the page title in the breadcrumb to reflect the new names:
Admins: "Knowledge Center Management"
Residents: "Knowledge Center"
If possible consider refactoring any file names or types to reflect this change to knowledge center. * We may have an issue with the backend models and database tables and need to discuss if it's worth refactoring that at this point.
- **Related issues**: 
- Closes: #521 
https://github.com/user-attachments/assets/322da206-61b7-4cb0-b4bd-605f509a3a09

Replace Open Content with Knowledge Center

---

backend/go.mod
backend/migrations/00025_add_login_count_table.sql
backend/src/database/users.go
backend/src/handlers/dashboard.go
backend/src/handlers/left_menu_handler.go
backend/src/handlers/login_flow.go
backend/src/handlers/server.go
backend/src/models/facilities.go
backend/src/models/logins.go
backend/src/models/users.go
config/kratos/kratos.yml
frontend/src/Components/EngagementRateGraph.tsx
frontend/src/Components/Navbar.tsx
frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Components/PeakLoginTimesChart.tsx
frontend/src/Pages/OperationalInsights.tsx
frontend/src/app.tsx
frontend/src/common.ts
provider-middleware/Dockerfile
provider-middleware/dev.Dockerfile
provider-middleware/handlers.go
provider-middleware/main.go
provider-middleware/video_dl.go

This adds an `Operational Insights` page visible by administrators. This also creates the necessary table to track logins/counts/and times across facilities and displays the data to admins.

feat: add layer 0 operational insights page w/ charts for user data

---

backend/src/database/open_content.go
backend/src/handlers/open_content_handler.go
backend/tasks/main.go
frontend/src/Components/FeatureLevelCheckboxes.tsx
frontend/src/Components/Navbar.tsx
frontend/src/Components/forms/EditUserForm.tsx
frontend/src/Pages/AdminDashboard.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/MyProgress.tsx
frontend/src/Pages/OpenContentLevelDashboard.tsx
frontend/src/Pages/ProviderPlatformManagement.tsx
frontend/src/Pages/StudentDashboard.tsx
frontend/src/Pages/StudentLayer0.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/app.tsx
frontend/src/common.ts
frontend/src/routeLoaders.ts
frontend/src/useAuth.ts

Admins should see the following navigation menu:
Student Activity → This is the old “Dashboard”
Students → Links to the current Students page
Admins → Links to the current Admins page
Facilities → Links to the current Facilities page
Learning Platforms → This is the Provider Platform page.
Residents should see the following navigation menu:
My Courses → Links to the current My Courses page
My Learning → This is the old dashboard.
- **Related issues**:
Closes: #509
https://github.com/user-attachments/assets/9f9acbe7-42eb-45c6-8d00-b6745ce5f293

Update navigation for Level 2 access

---

provider-middleware/kiwix_data.go

This checks the byte size of the image being downloaded for the library thumbnail, if it is below the constant of 2048 bytes, it sets the filename and therefor the default thumbnail URL for the library to the kiwix thumbnail helping to avoid blank images when displaying libraries in the Dashboard or the Knowledge center. 
- **Related issues**: Closes #567 
Also adds a check in ParseUrls in which if there is an error in downloading the thumbnail it will default to the Kiwix thumbnail.

fix: Default to Kiwix thumbnail for small image libraries

---

backend/tasks/database.go
backend/tasks/main.go
backend/tasks/scheduler.go

This adds the necessary logic for cron job scheduling of Brightspace tasks. 
- **Related issues**: Closes #545 
This checks the provider type against Brightspace, if the tasks provider type is of type models.Brightspace then at 1am getCourses will run, at 2am getMilestones will run, and at 3am getActivity will run. Given the https nature of Brightspace this implementation had to be tested on an instance of the development product configured for https, and then ported over to the regular non-https instance of the product. This branch brightspace_cron is a non-https ported branch, that which is running https tested code, just for reference.

feat: add cron scheduling for Brightspace

---

backend/src/database/user_catalogue.go
backend/src/handlers/dashboard.go
backend/src/handlers/dashboard_test.go
frontend/src/Pages/MyProgress.tsx
frontend/src/common.ts

Validated that all of the following are displayed on the 'My Progress' page:
- Number of courses completed
- Number of courses in progress
- Time spent working on course material
- Course listing (completed and in progress)
- Activity view (removed from My Progress page)
Also, I have documented how each of the numbers is calculated here: https://github.com/UnlockedLabs/UnlockEdv2/wiki/Course-Progress-Calculations
I modified the SQL query to correctly group the database records along with summing the total time spent working on course material. I also added logic for retrieving the number of 'in progress' courses. 
- **Related issues**: Closes #528.

feat: add in progress to user my progress page and remove activity chart per #528

---

backend/tasks/scheduler.go
frontend/src/Components/FavoriteCard.tsx
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Pages/OperationalInsights.tsx

This adds a tooltip "Unavailable Content" to any favorited content that has been disabled by an Admin since being favorited. Also fixes an admin check on the Library Card that was causing the favoriting star not to be rendered for students. Also adds appropriate spacing in Operational Insights 
- **Related issues**: Closes #566 Closes #576

fix: add tooltip to make users aware of disabled favorited content

---

provider-middleware/kiwix.go

This change just updates one of the logging statements to include the Kiwix library name. 
Before
>Attempting to update existing Kiwix Libraries.","time":"2024-12-11T17:14:34Z
After
>Attempting to insert or update library from Kiwix: Termux Wiki","time":"2024-12-11T19:51:36Z

refactor: modified logging statement to include library name

---

backend/tasks/database.go
frontend/src/Components/inputs/DropdownInput.tsx
frontend/src/Components/inputs/TextAreaInput.tsx
frontend/src/Components/inputs/TextInput.tsx

for whatever reason, `as string` shuts the lints up.
Also prevent the scheduler from creating/updating the tables that are embedded relationships in the struct.

fix: prevent scheduler from updating relation on task, frontend lints

---

backend/src/models/jobs.go
backend/tasks/database.go
backend/tasks/scheduler.go
provider-middleware/handlers.go
provider-middleware/middleware.go

This improves the flow of the scheduled jobs, prevents blocking all other tasks if a provider is found with no courses, allowing the OCP tasks to run on first go. Simplifies the general flow.

simplify the cron scheduling, remove blocking for first run to get courses

---

backend/migrations/00029_alter_open_content_favorites_table.sql
backend/src/database/helpful_links.go
backend/src/database/libraries.go
backend/src/database/open_content.go
backend/src/database/videos.go
backend/src/handlers/open_content_handler.go
backend/src/handlers/open_content_handler_test.go
backend/src/handlers/video_handler.go
backend/src/models/open_content.go
backend/src/models/video.go
frontend/src/Components/OpenContentItemAccordion.tsx
frontend/src/Components/VideoCard.tsx
frontend/src/Pages/StudentLayer1.tsx
frontend/src/common.ts

Updated the Resident's Trending Content page to display Libraries, Videos, and Helpful Links into collapsible sections with an icon. 
I implemented each category to contain at most 10 content items (always most recent) to avoid overloading the screen with too much content.
There were also bugs associated with video favorites that were located during this implementation and were corrected. 
Would like to demo for Chris to see if there are any additional adjustments that are required.
- **Related issues**: Closes #550".

Layer 1 Resident Dashboard > Organize Favorites by Content Type #550

---

backend/src/handlers/helpful_links_handler.go
frontend/src/Components/ULIComponent.tsx
frontend/src/Components/cards/HelpfulLinkCard.tsx
frontend/src/Pages/HelpfulLinks.tsx
frontend/src/Pages/HelpfulLinksManagement.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/OpenContentManagement.tsx
frontend/src/Pages/StudentLayer1.tsx
frontend/src/app.tsx
frontend/src/common.ts

Adds helpful links page, fixes some other small bugs
- **Related issues**: Closes #602 closes #604 closes #603 

feat: add helpful links tab to student view, other bug fixes

---

frontend/src/Components/FeatureLevelCheckboxes.tsx

Changes Knowledge Center in the Super Admin feature check boxes to "Knowledge Base"
- **Related issues**: Closes #597

fix: change Knowledge Center to Knowledge Base

---

frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/StudentManagement.tsx

Add correct pencil icon in admin management page.
Removed old button classes for add admin and add student, and replaced with the button class.
- **Related issues**: Closes #619

fix: add button class on  Admin and  Student page, and pencil icon fix

---

frontend/src/Components/TitleManager.tsx
frontend/src/Pages/LibraryViewer.tsx
frontend/src/app.tsx
frontend/src/common.ts

This PR adds dynamic title changes for pages. In the library viewer the TitleManager checks to see if we are in the library viewer, if we are it gives an explicit 5 second timeout to wait for the iFrame to load the content, after that pulls the title tag from inside of the document and then renders it as the Title for the parent DOM. 
- **Related issues**: Closes #610 
1'st layer 
2'nd nested layer inside of the library viewer 
5 layers deep
There is an issue in which if the user clicks on a link inside of the iFrame that is cross-site, the title will not change, and there will be errors in the console, but, this does not effect any of the functionality outside of that.

fix: add titles for pages

---

backend/src/database/libraries.go
backend/src/database/videos.go
backend/src/handlers/libraries_handler.go
frontend/src/Components/CatalogCourseCard.tsx
frontend/src/Components/EnrolledCourseCard.tsx
frontend/src/Components/ProviderCard.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/StudentManagement.tsx

- #592 
- Consisted of adding logic to the library handler to use the parameter value 'featured' when resident navigates to Trending Content page.
- #617 
- Consisted of adding CSS style 'cursor-pointer' to interactive icons.
- #612 
- Consisted of swapping positions of the Course title and Platform provider. Also modified Javascript to not display bullet point when there is no start/stop date displayed.
- #627 
- Consisted of modifying the query that is used for favoriting the library. The issue was due to the user id not being part of the criteria of the query.
- #629 
- Consisted of modifying the query that is used for pulling libraries to display when navigating to the 'Knowledge Center Management'.  I also modified the query for favoriting to allow the feature toggle to work …

Fixes for hover-state icons, display of course titles, featuring functionality, and favoriting per issues #592, #617, #612, #627, #629 

---

frontend/src/Components/dashboard/FeaturedContent.tsx

Adds a dotted outline library shaped line around where a Library card would be in the Knowledge insights that is optionally clickable, when an admin clicks on the box it will redirect them to libraries so that they can feature content. 
- **Related issues**: Closes #634

fix: add dotted box to indicate no featured content on knowledge insights

---

frontend/src/Components/cards/HelpfulLinkCard.tsx
frontend/src/Components/forms/EditLinkForm.tsx

Fixes user being navigated away from the helpful links page when they click on a link, the user will now stay on the helpful links page in the original tab, without switching from admin to student view and vice versa. Also persists the "name" of the helpful link upon edit. 
- **Related issues**: Closes #642 Closes #644 
When i hit ESC in the modal, the form doesnt escape because the other bug I just fixed hasn't been merged in yet, that issue shouldn't persist after my last PR gets merged. 
https://www.loom.com/share/e3668c6b30db47388a665bd5647510cf?sid=ac98bdcc-696a-41ad-916b-fa06f0169dff

fix: fix helpful links name persistence and accidental navigation on helpful links

---

frontend/src/Components/Navbar.tsx
frontend/src/useAuth.ts

- #611
- Consisted of moving html elements around as well as some css due to the gap between the logo and top list item.
- #647 
- Consisted of modifying and conditionally displaying html per layer selected and reworking some javascript to handle the page that gets displayed to the user based on the layer selected.
- **Related issues**: closes #611, closes #647

Fixes for moving links on menu and layer inconsistencies

---

frontend/src/Components/Modal.tsx
frontend/src/Components/forms/EditFacilityForm.tsx
frontend/src/Components/forms/EditProviderForm.tsx
frontend/src/Components/forms/EditUserForm.tsx

This PR makes sure that modal forms are reset to defaults, and or relevant data when a user exits out of them through the ESC key. Prior to this if you opened a modal, input data, and then used the ESC key to exit, it was holding onto that stale input/data/information, this no longer happens. 
- **Related issues**: Closes #638 
https://www.loom.com/share/d0edbeac9c754cdfbcb0ebd52fcdbb47?sid=4eae16cd-3dc7-4aca-8041-c56a3087af0b

fix: modals reset now upon close and reopen

---

.github/workflows/add-needs-verification-label.yml

…ed to Done
This workflow is triggered when an issue is moved to the "Done" column in the project board. It automatically adds the "Needs verification" label to the issue. The label will be used to indicate that the issue needs to be verified in the staging deployment before it can be considered fully resolved. Once the verification is complete, the label can be manually removed by the person validating the issue.
Please include any additional context or information that the reviewer may …

feat: add workflow to label issues with "Needs verification" when moved to Done

---

backend/src/database/activity.go
backend/src/database/helpful_links.go
backend/src/database/seed_demo.go
backend/src/handlers/dashboard.go
backend/src/handlers/dashboard_test.go
backend/src/models/course.go
frontend/src/Pages/AdminLayer2.tsx
frontend/src/common.ts

Update the Admin Layer 2 Dashboard for student activity (named Learning Insights) so that it shows the data relative to courses, student enrollments and activity time, all which have the option to be filtered by facility
- **Related issues**: #530

Learning insights dash

---

frontend/src/Components/FavoriteCard.tsx
frontend/src/Components/FeatureLevelCheckboxes.tsx
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/VideoCard.tsx
frontend/src/Components/cards/HelpfulLinkCard.tsx
frontend/src/Components/forms/AddLinkForm.tsx
frontend/src/Components/forms/EditLinkForm.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/FacilityManagement.tsx
frontend/src/Pages/HelpfulLinksManagement.tsx
frontend/src/Pages/ProviderPlatformManagement.tsx
frontend/src/Pages/ProviderUserManagement.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/Pages/VideoManagement.tsx

Updates all toasters to be capitalized. Also condenses some of the toggle functions into one.
- **Related issues**: #615

fix: standardize toaster messages

---

frontend/src/Components/dashboard/FeaturedContent.tsx

Fixes there being a "Featured Content" box if there is no featured content and the user is not an admin.
- **Related issues**: Closes #654 
Student side is on the left, admin is on the right.

fix: remove featured content box if empty and not admin

---

.github/PULL_REQUEST_TEMPLATE.md

A page was added to the repository wiki (https://github.com/UnlockedLabs/UnlockEdv2/wiki/Deprecated-Features-and-Components) to track when we remove deprecated features & components. 
This change updates the PR template to remind the author to update the wiki page when they remove features or components that might be reintroduced or took significant development.

chore: updated pr-template

---

config/proxy.Dockerfile
config/squid.conf
provider-middleware/Dockerfile

This will get squid up and running in our cluster

feat: add squid proxy dockerfile and config

---

frontend/src/Components/Navbar.tsx
frontend/src/Components/PageNav.tsx
frontend/src/Components/VideoEmbedViewer.tsx
frontend/src/Layouts/AuthenticatedLayout.tsx
frontend/src/Pages/AdminLayer2.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/CourseCatalog.tsx
frontend/src/Pages/FacilityManagement.tsx
frontend/src/Pages/LibraryViewer.tsx
frontend/src/Pages/MyCourses.tsx
frontend/src/Pages/MyProgress.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/OpenContentManagement.tsx
frontend/src/Pages/OperationalInsights.tsx
frontend/src/Pages/ProviderPlatformManagement.tsx
frontend/src/Pages/StudentLayer1.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/app.tsx
frontend/src/common.ts

This PR removes the breadcrumbs from the PageNav, removes the h1 headder tags for the page names throughout the application, I use the react-router-dom's useMatches and the route's title attribute to name the pages and then place those in the respective spot where the old breadcrumbs were, I also made the Home icon navigable, and changed "students" to residents in app.tsx as that is the language we are trying to move to, and I was in there.  
- **Related issues**: Closes #640 
Admin and student walk through
https://www.loom.com/share/8461ef4247fd4b93b878f457cd4cb703?sid=ea7b1cef-ac49-402d-bcda-2ef88f998f09

fix: remove breadcrumbs, move page titles

---

frontend/src/Components/dashboard/ResidentWeeklyActivityTable.tsx
frontend/src/Pages/StudentDashboard.tsx
frontend/src/routeLoaders.ts

Fixes error for no activity pulled

fix: handle for no activity or courses student layer 2 dash

---

frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Components/PageNav.tsx
frontend/src/Components/VideoEmbedViewer.tsx
frontend/src/Pages/AdminLayer1.tsx
frontend/src/Pages/AdminLayer2.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/CourseCatalog.tsx
frontend/src/Pages/FacilityManagement.tsx
frontend/src/Pages/LibraryViewer.tsx
frontend/src/Pages/MyCourses.tsx
frontend/src/Pages/MyProgress.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/OpenContentManagement.tsx
frontend/src/Pages/OperationalInsights.tsx
frontend/src/Pages/Programs.tsx
frontend/src/Pages/ProviderPlatformManagement.tsx
frontend/src/Pages/StudentDashboard.tsx
frontend/src/Pages/StudentLayer1.tsx
frontend/src/Pages/StudentManagement.tsx

Modified CSS padding styles on several pages for aligning Page titles with the content found on the pages. 
- **Related issues**: Closes #663.

fix: modify css and add conditional for left-aligning page titles with content on page per #663

---

frontend/src/Components/CatalogCourseCard.tsx
frontend/src/Components/ClampedText.tsx
frontend/src/Components/EnrolledCourseCard.tsx
frontend/src/Components/VideoCard.tsx

- #673 
- Modified CSS to fix the position of the progress bar at the bottom of card.
- Added javascript and an html element to handle displaying the browser tooltip when course title is truncated
- Modified javascript date formatter to display 2 digits for day rather than a numeric to align with MM/DD/YYYY format
- #679 
- Moved onClick handler to parent div HTML element of the Video Card
- **Related issues**:  Closes #673, Closes #679.

Fixes for making entire video card clickable and enhancing course card display

---

backend/src/database/open_content.go
backend/src/models/open_content.go
frontend/src/Components/FavoriteCard.tsx
frontend/src/Components/OpenContentItemAccordion.tsx
frontend/src/Components/cards/OpenContentCard.tsx

Modified the associated SQL queries to not filter out favorites associated to hidden libraries. Also added CSS to disable the content card from being clickable and added tooltip text per request.
- **Related issues**: Closes #672 .

fix: modify logic to not hide favorited content items and rather disable them

---

backend/seeder/main.go
backend/src/database/libraries.go
backend/src/handlers/libraries_handler.go
backend/src/models/library.go
backend/src/models/open_content.go
docker-compose.yml
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/LibrarySearchResultsModal.tsx
frontend/src/Components/cards/LibrarySearchResultCard.tsx
frontend/src/Components/dashboard/FeaturedContent.tsx
frontend/src/Components/inputs/LibrarySearchBar.tsx
frontend/src/Components/inputs/MultiSelectDropdownControl.tsx
frontend/src/Components/inputs/SearchBar.tsx
frontend/src/Components/inputs/index.ts
frontend/src/Pages/LibraryViewer.tsx
frontend/src/app.tsx
frontend/src/common.ts
frontend/src/routeLoaders.ts
provider-middleware/kiwix.go
provider-middleware/kiwix_data.go

Initial design and implementation of doing full text searching across kiwix libraries.  This change required deploying our own managed kiwix server within the 'staging' development environment so that we could manage Kiwix's API to perform full text searching.
- A Kiwix server was set up to provide control and customization over our search functionalities. 
- Libraries will need to be manually downloaded to the Kiwix server as part of the setup and maintenance process. 
- We need to ensure sufficient disk space is allocated on the server for storing library zim files--could grow significantly depending on the number of zim files downloaded.
- **Related issues**: "Closes #639 ".
No additional context.
If any core features or components were removed with this PR, please note them here so …

Kiwix search implementation

---

backend/src/database/helpful_links.go
frontend/src/Components/Navbar.tsx
frontend/src/Components/cards/HelpfulLinkCard.tsx
frontend/src/Pages/HelpfulLinks.tsx
frontend/src/useAuth.ts

NOTE: In screenshot below for ticket #658, I highlighted an icon, confirming if this icon is correct for 'Trending Content'?)
- #658 
- Modified/Removed Javascript associated with layering changes
- Modified/Moved around HTML elements.
- #678 
- Modified CSS on the helpful link card to be consistent with how the LibraryCard is styled. (Clickable Cursor Icon, Bottom Border Below Title, Horizontal Alignment of Image and Title). Also, #682 is related to this modification
- Added tooltip to favorite icon
- Added missing pager component to the Helpful links page
- #692 
- Added criteria to the SQL scalar query to join on open_content_provider_id between the tables open_content_favorites and helpful_links. 
- #667 
- Changed icons for Trending Content and Learning Path on the nav bar
- …

Fixes for admin and resident side nav, helpful link card consistency, and unfavoriting a helpful link per issues #658, #678, and #692

---

frontend/src/Components/dashboard/ExpandableCardGrid.tsx
frontend/src/Pages/StudentLayer1.tsx

When introducing the `ExpandableCardGrid` I made a mistake and didn't apply the four-column layout for the helpful links. This fix adds a cols prop to the grid and sets the Featured content at 3 cols and Helpful links at 4 cols.

fix: wrong col count for helpful links

---

backend/src/database/helpful_links.go
frontend/src/Components/forms/AddLinkForm.tsx

Adds toaster message for "Link already exists". 
- **Related issues**: closes #643

fix: add existing helpful link toast

---

frontend/src/Components/VideoCard.tsx

Added a call to stopPropagation() on the mouse event to stop the bubbling of the event up to the parent div element.
**Related issues**: Closes #703
[FixedFavoriting.webm](https://github.com/user-attachments/assets/ba043599-7bd4-4846-bdcb-acb938a236e3)

fix: add line of javascript to fix favoriting and unfavoriting a video card per #703

---

backend/src/handlers/dashboard.go
backend/src/handlers/dashboard_test.go
backend/src/handlers/server.go
backend/src/models/course.go
backend/src/models/dashboard.go
frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Pages/AdminLayer2.tsx
frontend/src/common.ts

This pull request adds a cache for the admin layer 2 dashboard/learning insights.  
- **Related issues**: Closes #685 
Had to add a little bit of redundant code to test if we are testing because NATS isn't running during testing.

fix: add NATS cache to AdminLayer2

---

frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/StudentManagement.tsx

This PR fixes the Admin and Student management page order by drop downs. It fixes the previous Arrow icons, removing them, and adding "Newest" and "Oldest". This PR also adds the Created At column to show the user when the account was created. 
- **Related issues**: Closes #711 
Created At column was added as a result/conversation with Josh after I had grabbed the ticket.

fix: fix order by add created at

---

frontend/src/Components/forms/AddLinkForm.tsx
frontend/src/Pages/StudentManagement.tsx

This increases the allowed length of the URL for helpful_links, after some research I have found that the most common character count for URL's is between 80-100 characters long, given that the actual url is not displayed and the user explicitly names the url. In the database we limit the URL to 255 characters so the URL character limit has been updated to be 255 characters. Secondly, the "Add Students" button has been changed to "Add Residents" and in the form. 
- **Related issues**: Closes #707 Closes #709 
**Helpful Link URL -> Description field is the URL for character count length reference**

refactor: change add student to add resident, change url length

---

backend/src/handlers/helpful_links_handler.go

Thumbnails on helpful link's weren't being rendered properly because at times the response status code would actually be 200, but there still would be no favicon. We fix this by checking whether or not the actual content-length of the response is 0 or less, and if it is, assign the ULL logo. 
- **Related issues**: Closes #725 
**Reference the few links copied from staging that weren't working**

fix: fix helpful link thumbnail issue

---

backend/src/handlers/login_flow.go
frontend/src/Components/forms/ConsentForm.tsx
frontend/src/Components/forms/LoginForm.tsx
frontend/src/Pages/Error.tsx
frontend/src/Pages/Welcome.tsx
frontend/src/app.tsx
frontend/src/common.ts
frontend/src/useAuth.ts

#754 
previously it would check the flow, and because the user is logged in, it would assume that it's a user trying to oauth into the platform, and send a request to the backend with the auth flow to `/api/auth/refresh`, which would then `502` because it's relying on a parameter that isn't present.
This checks for a user already logged in and if an oauth2 challenge isn't found, it will simply redirect them to `/authcallback`, if the `flow_id` isn't valid, then it redirects them to `/self-service/login/browser` to get a new `flow_id`

fix: login/auth issue for stale or invalid flow ids

---

backend/migrations/00033_update_admin_roles.sql
backend/src/database/programs.go
backend/src/database/users.go
backend/src/handlers/auth.go
backend/src/handlers/dashboard.go
backend/src/handlers/programs_handler.go
backend/src/handlers/server_test.go
backend/src/handlers/user_handler_test.go
backend/src/models/users.go
frontend/src/Components/Navbar.tsx
frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Components/PageNav.tsx
frontend/src/Components/dashboard/ExpandableCardGrid.tsx
frontend/src/Components/forms/CreateProgramForm.tsx
frontend/src/Pages/AdminLayer2.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/HelpfulLinksManagement.tsx
frontend/src/Pages/Programs.tsx
frontend/src/app.tsx
frontend/src/common.ts
frontend/src/useAuth.ts
provider-middleware/kiwix.go

This pull request slightly revamps the admin roles and abilities. Pre this pull-request we had two different types of admins, system admins, and admins, system admins were presumed to be a member of Unlocked Labs, while admins were presumed to be an administrator user from the department of corrections. This had very little separation of concerns and warranted a standard admin to access every facility within that running instance of the applications database, warranting potential worrisome conditions, as a department of corrections may not want an administrator from one facility having power over the users, and or admins of another facility. We fix this concern in this pull request by creating Department Admins, and Facility Admins, System Admins did not change. Currently this does not …

feat: add dept admin, add facility admin

---

docker-compose.yml

fix bug where postgres tries to run the zims.sh file when starting containers

fix: dont mount shell script to pg docker container

---

backend/src/database/users.go

prevents facility_admin from viewing all users in the 'admins' page
closes #781

fix: add facility_admin to role list in user query

---

frontend/src/Components/FavoriteCard.tsx
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/VideoCard.tsx
frontend/src/Components/cards/HelpfulLinkCard.tsx

This PR removes the ability of admins to favorite while in preview mode on Libraries, Helpful Links, and Videos. 
- **Related issues**: Closes #771 
https://www.loom.com/share/1b6986f253a04f1fbebea7477f5f103e?sid=fde981af-4d93-4ee2-aaec-866eaa29bb6f
---
- https://app.asana.com/0/0/1209457884707537

fix: remove admin ability to alter data in student view

---

frontend/src/Components/Navbar.tsx
frontend/src/Components/TabView.tsx
frontend/src/Pages/ResidentHome.tsx
frontend/src/Pages/StudentLayer0.tsx
frontend/src/Routes/App.tsx
frontend/src/Routes/KnowledgeCenterRoutes.tsx
frontend/src/useAuth.ts

This pull request adds more tab separation in our "TabView" so that on the parts of the application that uses tabs there is more intuitive tab navigation. It also changes StudentLayer0 (which is essentially if the user has 0 features enabled) to "/temp-home" and added a "Contact your administrators" dialogue to help assist them in why they're at that page. Also, StudentLayer1 (trending content) was changed to "ResidentHome", and also assigned the "/home" route. 
- **Related issues**: Closes 32 and 57 in Asana
**This is now the StudentLayer0 when no features are available**

feat: add proper tab separation change trending content to home

---

.github/workflows/container_builds.yml

Added conditional check for setting the docker image version used for images are that built within the workflow file named container_builds.yml.  For pushes to the beta branch the version will be 'beta' and for all other branches the version will be 'latest'.
- **Related issues**: This issue is related to ticket [Beta Deployment Site](https://app.asana.com/0/1209460078641109/1209552658203933/f)

feat: add logic to determine docker image version name

---

backend/src/handlers/utils.go
frontend/src/Components/LibraryLayout.tsx

Within the LibraryLayout.tsx (in Knowledge Center)
- Modified the ordering parameters found within the request url used to retrieve libraries. The ordering parameters were changed from created_at/desc TO title/asc.
- **Related issues**: Link to issue on asana task: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209485908694611?focus=true

fix: change order by of libraries within the knowledge center to be by title ascending per asana task 40

---

backend/src/handlers/auth.go
backend/src/handlers/server.go
backend/src/handlers/user_handler.go
backend/src/handlers/utils.go
frontend/src/Components/forms/ChangePasswordForm.tsx

cleans up a couple things from adding the audit logs, and re-enables the new facility name + timezone form when the SuperAdmin makes their password for the first time. 
also follows new Go convention/warnings and replaces interface with any type in a few areas.

fix: display proper form on initial password reset, add logs

---

backend/src/database/libraries.go
backend/src/handlers/libraries_handler.go

Added a new method within the database layer for retrieving all english language libraries and modified handler to call this method. 
When doing a search through all libraries it throws an exception because kiwix only allows you to search through libraries of one language type (eng) only. This was already being handled when a user selects, via checkboxes, which library they want to search through. It filters for 'eng' type libraries only. 
The error message you receive when you search through libraries of all language types is:   
- "Two or more books in different languages would participate in search, which may lead to confusing results."

fix: add method to retrieve all english language libraries to avoid kiwix mutiple language error

---

backend/src/database/courses.go
backend/src/database/libraries.go
backend/src/database/milestones.go
backend/src/database/open_content.go
backend/src/database/outcomes.go
backend/src/database/program_sections.go
backend/src/database/programs.go
backend/src/database/users.go
backend/src/database/videos.go
backend/src/handlers/proxy_handler.go
backend/src/handlers/utils.go
backend/src/models/resource.go

this adds a couple convenience methods for the `QueryContext` struct that is slowly being integrated into all of our queries.
`SearchQuery()` + `OrderClause()` that just removes the need to do `"%' + args.Search + "%"` and `args.Order + " " args.OrderBy`
Also this passes the request context into the database calls, ensuring to cancel the context if the request times out.

refactor: add request context to all db calls using queryCtx

---

frontend/src/Components/FacilityCard.tsx
frontend/src/Components/LibraryCard.tsx
frontend/src/Components/modals/FormModal.tsx
frontend/src/Components/modals/TextOnlyModal.tsx
frontend/src/Pages/HelpfulLinksManagement.tsx

We had unnecessary scrollbars (horizontal and vertical) that appeared on pages that included modals and tooltips that went off screen. This PR makes the following change:
* Removes the `relative` class from the modals. It didn't appear to be necessary.
* Changes the tooltip position on the Library Card for the Library Card and on the Facilities page to push to the left.
Resident:
Knowledge Center → Libraries — excess horizontal
Knowledge Center → Helpful Links — excess horizontal
Admin:
Knowledge Center Management → Libraries — excess horizontal
Knowledge Center Management → Videos — excess vertical
Knowledge Center Management → Helpful Links — excess vertical
Resident Management → excess vertical
Admin Management → excess vertical
Facility Management — excess horizontal, excess vertical …

fix: removed horizontal and vertical scrollbars

---

backend/src/handlers/user_handler.go
frontend/src/Components/FavoriteCard.tsx
frontend/src/Components/VideoCard.tsx
frontend/src/Components/cards/OpenContentCard.tsx
provider-middleware/video_dl.go

the Video thumbnails kept resetting for some reason. since we are storing them on the backend as `external_id.jpg`, we can just read them from the backend in the same format.
this also prevents any admin from `curl`ing a post request to reset any other admin's password

Fix pass reset permissions and video thumbnail issues

---

backend/src/database/program_sections.go
backend/src/handlers/programs_handler.go
backend/src/handlers/sections_handler.go
backend/src/handlers/sections_handler_test.go
backend/src/models/program_sections.go
frontend/src/Components/SectionStatus.tsx
frontend/src/Components/inputs/CancelSubmitRow.tsx
frontend/src/Components/inputs/ConfirmButton.tsx
frontend/src/Components/modals/ModifySectionModal.tsx
frontend/src/Components/modals/TextOnlyModal.tsx
frontend/src/Pages/ProgramOverviewDashboard.tsx
frontend/src/common.ts

Admins are now able to manually update the status of the sections, which are displayed inside the program from the program management page. Some notes to consider before merging this PR are below.
- **Related issues**: [Change section status](https://app.asana.com/0/1209460078641109/1209693986941448/f)
Brief video of the functionality:
https://github.com/user-attachments/assets/c8b21519-fc66-40cc-bbae-1bce70d5dc0c
Furthermore, if the section is not allowed to be archived due to having students and either being in the ACTIVE or SCHEDULED states, the following will appear when they attempt to archive the section. This will NOT allow the invalid section to be archived, but will archive the valid section.
There are a few changes that might require a migration (if we feel significant enough), …

feat: add section status modification and archiving

---

backend/migrations/00043_add_doc_to_users.sql
backend/src/database/users.go
backend/src/handlers/auth.go
backend/src/handlers/user_handler.go
backend/src/models/resource.go
backend/src/models/users.go
frontend/src/Components/modals/index.ts
frontend/src/Pages/ResidentProfile.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/common.ts

This pull request: 
- 	Adds the ability for an admin to add the users DOC number during creation
- 	Adds the ability for an admin to search for the user with their DOC number
- 	Adds the residents DOC number to the profile overview page
- **Related issues**: Closes id 38 
https://app.asana.com/0/1209460078641109/1209485070839620/f

feat: add doc number to profile overview and search

---

frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/Navbar.tsx
frontend/src/Components/UnlockEdTour.tsx
frontend/src/Components/modals/FormModal.tsx
frontend/src/Context/TourContext.tsx
frontend/src/Pages/LibraryViewer.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/ResidentHome.tsx

Fixes a few bugs related to welcome tour, including:
- users click on "knowledge center" and then click back when prompted with "Welcome to the Knowledge Center. Here, you can find a range of resources in both written and video format, as well as helpful links.". It now allows you to click on knowledge center again.
- Click on the specific library and see the pop-up: "Here, you can see everything inside the library." Click the Back button on this pop-up. should take you back to be able to click into the library.
- clicking back from the "top content" pop up takes you back to library viewer sub page favorite pop up.
- Adds steps to the tour so the user can tell how far along they are
- changes the code to refer to the step by its target id, rather than by the step index for easy updating …

fix: update bug fixes on tour

---

frontend/src/Components/modals/index.ts
frontend/src/common.ts

This PR fixes the doc_id in the admin flow
- **Related issues**: closes asana id # 113
resident 
Admin
https://app.asana.com/0/1209460078641109/1209864919491806/f

fix: remove doc_id for admins

---

frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/VideoContent.tsx
frontend/src/Hooks/paginationUrlSync.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/FacilityManagement.tsx
frontend/src/Pages/Favorites.tsx
frontend/src/Pages/HelpfulLinks.tsx
frontend/src/Pages/HelpfulLinksManagement.tsx
frontend/src/Pages/OpenContent.tsx
frontend/src/Pages/OpenContentManagement.tsx
frontend/src/Pages/ProgramManagement.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/Pages/VideoManagement.tsx

PR Does: 
- Fixes the tab navigation/highlighting on the knowledge center, so that if you hit back and your last page was in the knowledge center, it navigates accordingly
- Updated pagination so that it is pushed onto the browsers history stack (through the url) so that if you navigate through pages, you are able to go back. 
- **Related issues**: closes ID # 83 in Asana 
https://github.com/user-attachments/assets/30545fc1-8223-4fa9-9751-042b84086ba5
This is a slightly different paradigm for our pagination, previously we were only adding the pagination information in the url of the api, this pr does add it to the actual visible url, we could have possibly used react routers navigate state, but this is ephemeral and would not persist across full page refreshes so, i thought that although …

fix: fix history navigation

---

backend/src/database/DB.go
backend/src/database/users.go
backend/src/handlers/auth.go
backend/src/handlers/user_handler.go
backend/src/models/program_classes.go
backend/src/models/users.go
frontend/src/Components/EngagementRateGraph.tsx
frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Components/cards/AccountHistoryRowCard.tsx
frontend/src/Components/cards/index.tsx
frontend/src/Components/helperFunctions/calculateEngagementMetrics.tsx
frontend/src/Components/inputs/DropdownControl.tsx
frontend/src/Pages/ResidentProfile.tsx
frontend/src/common.ts

- Updates a few UI things on resident profile page (not specific to this ticket) but just to keep the UI consistent with other pages.
- changes the top libraries/recently viewed videos to one card with a toggle
- adds in account history card with pagination (UI)
- adds the backend for adding account history with the following actions
- account creation
- resetting a password by an admin
- setting a password by the user
- added to a facility (only on account creation)
- **Related issues**: Closes [Capture & Display User Activity ](https://app.asana.com/0/1209460078641109/1209825280254697/f)
https://github.com/user-attachments/assets/d880757a-8480-4223-b1d4-afcda8b3af76

feat: update resident profile and add account history

---

frontend/src/Components/TransferSummaryPanel.tsx
frontend/src/Components/forms/MapUserForm.tsx
frontend/src/Components/modals/CompletionDetailsModal.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/ProviderUserManagement.tsx
frontend/src/Pages/StudentManagement.tsx

Reformats how we display users first and last name in tabular places. 
- **Related issues**: Closes Asana #109
I went through all of the cases on our frontend where we render name_first and name_last, I thought this was going to be a bigger ticket, so I'm not going to guarantee I didn't miss anywhere's but, i'm pretty sure I didn't...there's a couple places that we didn't change, like the Resident Profile, and any user facing places where it sounds more natural, or conversational to keep the users first name last name. 
---
- https://app.asana.com/0/0/1209855394721661

fix: fix display format of user names

---

frontend/src/common.ts

moves "Other" to bottom of the funding type enum 
- **Related issues**: closes asana 117
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209876762905717?focus=true

fix: move other to bottom of enum

---

frontend/src/Components/ResidentPrograms.tsx
provider-middleware/Dockerfile

A squiggly got into the end of the route in the frontend for resident programs.....:( sad day..quick fix.

fix: remove extra added brace in resident program route

---

backend/src/database/programs.go
backend/src/handlers/facilites_handler_test.go
backend/src/handlers/facilities_handler.go
backend/src/handlers/programs_handler.go
backend/src/handlers/server_test.go
frontend/src/Components/FacilityCard.tsx
frontend/src/Pages/FacilityManagement.tsx

PR Makes sure that only system admins can edit or delete facilities for the time being. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210022616266304?focus=true

fix: guarantee only system admins may edit or delete facility

---

frontend/src/Components/modals/TextOnlyModal.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/StudentManagement.tsx

Add user and admin specific language when displaying a users temporary password. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209876778899413?focus=true

fix: change password logic for admin and resident specificity

---

frontend/src/Components/inputs/DropdownInput.tsx
frontend/src/Components/modals/index.ts
frontend/src/common.ts

Fixes how timezones are being displayed, and adds an optional dispalyNames parameter to the DropdownInput for future enum display issues. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210072188481737?focus=true

fix: fix dropdown display names for timezones

---

frontend/src/Components/inputs/SubmitButton.tsx
frontend/src/Components/inputs/TextInput.tsx
frontend/src/Components/modals/FormModal.tsx
frontend/src/Components/modals/VerifyResidentModal.tsx
frontend/src/Components/modals/index.ts

Added functionality where the confirmation button should be disabled by default and only be enabled when the user enters the DOC ID correctly.
https://github.com/user-attachments/assets/b553af8e-1cf2-4dcf-a9fd-9802a3b942c2
---
- https://app.asana.com/0/0/1209928767233485

Enhance transfer validation logic

---

frontend/src/Layouts/AuthenticatedLayout.tsx

https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209485070839570
the navbar now correctly reflects the state when a navigation item is clicked.

fix: keep navbar pinned position across client route changes

---

backend/src/database/users.go
backend/src/handlers/dashboard.go
frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Pages/OperationalInsights.tsx
frontend/src/Routes/App.tsx
frontend/src/common.ts
provider-middleware/video_dl.go

https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210093059550570
removes ambiguity by not mixing admin and resident data in the operational insights page.
also prevents storing admin metrics in login_activity table

display only resident data in operational insights page

---

backend/src/handlers/programs_handler.go
frontend/src/Pages/ProgramOverviewDashboard.tsx

Clamp text for the instructor name and class name on the program overview dashboard 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209977398530322?focus=true
- 
Clamped -
Not clamped -

fix: clamp text on program overview dashboard

---

backend/src/database/class_enrollments.go
backend/src/database/program_classes.go
backend/src/handlers/classes_handler.go

This pull request makes sure that when an admin cancels a class all Enrolled students enrollment status is marked as Cancelled
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210072150791608?focus=true

fix: cancel enrollments upon cancelled class

---

backend/src/database/program_classes.go
backend/src/database/programs.go
backend/src/handlers/classes_handler.go
backend/src/handlers/programs_handler.go
frontend/src/Components/ClassLayout.tsx
frontend/src/Components/ClassStatus.tsx
frontend/src/Components/ProgramStatus.tsx
frontend/src/Components/modals/ModifyClassModal.tsx
frontend/src/Components/modals/ModifyProgramModal.tsx
frontend/src/Components/modals/TextOnlyModal.tsx
frontend/src/Pages/ClassManagementForm.tsx
frontend/src/Pages/ProgramManagement.tsx
frontend/src/Pages/ProgramOverviewDashboard.tsx
frontend/src/common.ts

Updates the Program Management page/table so that users can update the status of a Program 
- **Related issues**: Closes https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1209699133678261?focus=true 
There was a bug in my implementation of the Program Status pill that lead me to the same bug in Class Status pill where if you click on a status, and then exit out of the modal, you are unable to get the modal to open up again because the state variable is already assigned to that status, so that bug is fixed in class status as well.

feat: add ability to change program status 

---

backend/src/database/class_events.go
backend/src/handlers/class_events.go
backend/src/handlers/events_attendance_handler.go
backend/src/models/class_event.go
frontend/src/Components/helperFunctions/formatting.tsx
frontend/src/Pages/ClassEvents.tsx
frontend/src/Pages/Error.tsx
frontend/src/Pages/EventAttendance.tsx
frontend/src/common.ts

1. Makes sure that you can't update the date in the URL and get away with it. 
2. Make sure the date in the ClassEvents table matches the date in the url when you click on an event
3. Fix the backend GetRRule from truncating the final day. 
- **Related issues**: Asana id 186
The ticket only required that we make sure that users are unable to update attendance for future dates, but I noticed a couple more bugs while working on it. The date's weren't matching up because of a timezone issue with the date that the user clicks on in the attendance table it was a day ahead. Also, the backend was truncating the last day of class because it was stopping at 00:00, so I fixed how the rrule is gotten so that the 24 hours of the final day is included. 
Asana: …

fix: update url tampering on front and backend

---

backend/migrations/00049_add_change_reason_to_class_enrollments.sql
backend/src/database/class_enrollments.go
backend/src/handlers/class_enrollments.go
backend/src/models/program_classes.go
frontend/src/Components/ClassEnrollmentDetailsTable.tsx
frontend/src/Components/modals/FormModal.tsx
frontend/src/Pages/ClassEnrollmentDetails.tsx

Adds the ability to add a reason the enrollment status was changed when the enrollment status is anything but cancelled or completed. 
- **Related issues**: Asana id 191 
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210164202065522?focus=true

feat: add reason for change when updating enrollment 

---

frontend/src/Components/FacilityCard.tsx
frontend/src/Components/helperFunctions/formatting.tsx

Adds a helper function so facility timezone can display correctly (in case we need to use this in another page in the future). 
[Asana task 210](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210255593728311?focus=true)

fix: add helper func to format timezone string

---

backend/migrations/00050_add_failed_login_attempts_table.sql
backend/src/database/users.go
backend/src/handlers/login_flow.go
backend/src/handlers/user_handler.go
backend/src/handlers/utils.go
backend/src/models/logins.go
frontend/src/Components/forms/LoginForm.tsx
frontend/src/api/api.ts
frontend/src/common.ts

This pull request locks a user "out" if they have failed to login 5 times within a 15 minute period. 
The current implementation logs the first failed login attempt, and then the most recent logged in attempt, upon each attempted login the handler checks if the user is locked out, during that check we check to see if the first login was 15 minutes prior to our window duration (15 minutes) if it has been over 15 minutes then we reset the failed login attempts, if the user is locked out we render the amount of time left before they can attempt again and don't pass through the login attempt so no more counters get incremented. If a password is reset, we check if that user has any entries in the database table, and if they do, we reset the failed attempts object for that user in the table.
- …

fix: lock users out after 5 failed login attempts within 15 mins

---

frontend/src/Pages/ProgramOverviewDashboard.tsx

Changed label from Residents to Enrollments on the Program Overview Dashboard screen.
- **Related issues**: Link to Asana ticket [Change "Residents" to "Enrollments for "Active Enrollments" on Program Overview Dashboard](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210481100839371?focus=true)

fix: change Residents to Enrollments per ticket 284

---

backend/src/handlers/classes_handler.go
frontend/src/Pages/ProgramManagement.tsx
frontend/src/Pages/ProgramManagementForm.tsx
frontend/src/Pages/ProgramOverviewDashboard.tsx
frontend/src/Routes/Programs.tsx
frontend/src/app.tsx

This PR does
1. Stops facility admins from getting to the create and or edit program page. 
2. Updates the tooltip on the program management form
3. Removes the "Edit program" in the program overview dashboard for facility admins
4. Updates the route with a new DeptAdminProgramRoutes making sure even if a facility admin navigates to the respective URI they are redirected
5. Fixes a bug on the program overview dashboard page that was stopping the program outcomes chart from being populated for facility admins
6. Removes the "Add Program" button for facility admins 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210481100839376?focus=true

fix: facility admins can't add or edit programs

---

backend/src/database/class_events.go
backend/src/handlers/class_events.go
frontend/src/Components/EventCalendar.tsx
frontend/src/Components/inputs/CancelButton.tsx
frontend/src/Pages/ProgramClassManagement.tsx
frontend/src/Pages/Schedule.tsx
frontend/src/Routes/Programs.tsx
frontend/src/css/app.css
frontend/src/routeLoaders.ts

Added schedule tab in the Class Overview Page which contains a calendar view allowing admins to reschedule or cancel sessions for the specific class selected. 
DEPENDENT ON PR #901
**The changes for this PR are located within this COMMIT:** [[feat: add schedule tab to class dashboard with cal view per ticket 265](https://github.com/UnlockedLabs/UnlockEdv2/commit/de8bed958fcee299d976505eb83ad9ce297954eb)]
- **Related issues**: Link to Asana tickets [Add Schedule Tab to Class Dashboard with Calendar View](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210354107888964?focus=true)
---
- https://app.asana.com/0/0/1210487095566651

feat: add schedule tab to class dashboard with calendar view

---

frontend/src/Components/modals/TextOnlyModal.tsx

A bug was identified where the Class Status pill would not render the ModifyClassModal after cancelling by esc and attempting to switch the status again.
Solution:
Added an event listener to close the modal when the escape key is pressed, ensuring the modal can be properly dismissed.
https://github.com/user-attachments/assets/fca8ceda-a50b-421a-ab75-be065e5ed1ae
Related to: https://app.asana.com/1/1201607307149189/inbox/1209552815576329/item/1210272664885957/story/1210390032326801
---
- https://app.asana.com/0/0/1210272664885957

Fix: Class Status Pill Issue on Program Overview Dashboard 

---

backend/src/database/class_enrollments.go

Added SQL criteria to left outer join for only selecting Enrolled residents.
- **Related issues**: Link to Asana tickets [Issue with enrolling new residents when there is capacity](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210535950665370?focus=true)

fix: add criteria to query for fixing enrolling issue--ticket 313

---

backend/src/database/class_events.go
backend/src/handlers/class_events.go
backend/src/handlers/user_handler.go
frontend/src/Components/ResidentPrograms.tsx
frontend/src/Components/helperFunctions/formatting.tsx
frontend/src/Components/modals/ResidentAttendanceModal.tsx
frontend/src/Components/modals/index.ts
frontend/src/Pages/EventAttendance.tsx
frontend/src/common.ts

- **Related issues**: [Ticket 294](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210481100839428?focus=true)

feat: add resident attendance breakdown on resident overview

---

frontend/src/Components/OperationalInsightsCharts.tsx
frontend/src/Pages/OperationalInsights.tsx

Fixed operation insights bug so that facilities display in dropdown and also made sure that switching between the facilities was working. This required removing the useLoaderData call along with a bit of frontend refactor.
- **Related issues**: Link to Asana tickets [BUG: Operational Insights Doesn't Update When Switching Facilities](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210535405607307?focus=true)

fix: remove loader call and replace logic with facilities per ticket 310

---

backend/src/database/users.go
frontend/src/Pages/AdminManagement.tsx

Added the Role column to user table and added the action icons for delete, edit, and reset password. Also added the tooltips requested when disabled. Modified the SQL query to pull all department admin users no matter the facility selected in the facility dropdown.
- **Related issues**: Link to Asana ticket [Clean up and address confusion on the Administrators Page](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210089681287799?focus=true)

feat: add Role column, disabled icons w/tooltip to user admin pg

---

backend/tests/integration/facilities_test.go
frontend/src/Pages/ClassManagementForm.tsx
frontend/src/Pages/ProgramManagementForm.tsx

* Button components now track state
* State determines text on buttons
- **Related issues**: Link to Asana ticket [Submit Button text for User and Facility modals](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210608461992709?focus=true)
I know that we don't use forks but I don't have permissions ( as far as I can tell)  yet to just push
---
- https://app.asana.com/0/0/1210603606220523

Update: submit button text based on create/edit mode

---

backend/src/database/users.go
frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/VideoContent.tsx
frontend/src/Components/inputs/DropdownControl.tsx
frontend/src/Pages/AdminLayer1.tsx
frontend/src/Pages/AdminManagement.tsx
frontend/src/Pages/CourseCatalog.tsx
frontend/src/Pages/Favorites.tsx
frontend/src/Pages/HelpfulLinks.tsx
frontend/src/Pages/HelpfulLinksManagement.tsx
frontend/src/Pages/MyCourses.tsx
frontend/src/Pages/MyProgress.tsx
frontend/src/Pages/ProgramOverviewDashboard.tsx
frontend/src/Pages/StudentManagement.tsx
frontend/src/Pages/VideoManagement.tsx

1. Modified the SQL query used to pull data for the operational insights page. I wrapped the `SUM` function within a `COALESCE` function to handle null values that cause the page to error.
2. Fixed DropdownControl component bug. Removed the label feature and added the value to be used/set per load of page or user selection.
**NOTE** This is to fix an issue within the **maine** deployment
- **Related issues**: Link to Asana tickets 
- [Error viewing operational insights for 2nd facility](https://app.asana.com/0/home/1209552816160104/1210603280485519)
- [BUG: Video Filter Dropdown Glitch on https://maine.unlockedlabs.org](https://app.asana.com/1/1201607307149189/project/1207681524569251/task/1210346392552612?focus=true)
---
- To see the specific tasks where the Asana app for GitHub is being …

fix: add coalesce function to SQL query for to fix operational insights issue per ticket 321

---

backend/src/database/programs.go
frontend/src/Pages/ProgramManagement.tsx

Bug was found where the facility admins total programs was not reflected correctly in their program management page. This was due to a bug that totaled all programs for all days within the time filter. The solution was to extract the total programs and enrollments into its own query, only pulling the most recent date for these numbers.
- **Related issues**: Fixes [Asana Ticket ID-298](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210487095566664?focus=true). This should also address the issues we had with [ID-329](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210615552064401?focus=true), where the facility admin numbers were off (they are the same bug I believe, but correct if I misinterpreted the ticket(s)).
Below is what a super admin …

fix: total programs and enrollments for facility admin pull from latest date

---

frontend/src/Pages/AddClassEnrollments.tsx

The name was shown as `lastnamefirstname` with no space between it. Corrected it so that its `lastname, firstname`

fix: fixed last, first for add enrollments

---

config/zims.sh
provider-middleware/kiwix.go
provider-middleware/video_dl.go

Fixed the following issues:
- UnlockEd only pulling one less library than Kiwix server contains
- changed a kiwix api endpoint's start parameter value from 1 to 0. 
- UnlockEd unable to download YT videos
- removed a space from an argument within the yt-dlp command
- **Related issues**: Link to asana tickets: [UnlockEd only pulling one less library than Kiwix server contains](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210756515444541?focus=true) and [UnlockEd unable to download YT videos](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210769523245497?focus=true) 
ALSO: Fixed issue with `make init` due to 404 status code returning when attempting to download zim files
Video Issue: …

fix: unlocked not pulling correct number of libraries and not able to download videos

---

backend/src/database/program_classes.go
backend/src/models/program_classes.go
frontend/src/Components/ResidentPrograms.tsx
frontend/src/Pages/ClassEnrollmentDetails.tsx
frontend/src/common.ts

https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210605185296656
If any core features or components were removed with this PR, please note them here so that they can be added to the wiki (see [Deprecated features and Components](https://github.com/UnlockedLabs/UnlockEdv2/wiki/Deprecated-Features-and-Components)).

feat: added more descriptive text with segregated option

---

frontend/src/Components/AttendanceStatusToggle.tsx
frontend/src/Components/inputs/TextInput.tsx
frontend/src/Pages/EventAttendance.tsx

This PR isn't attached to an open ticket. 
The Attendance page (`EventAttendance`) was improved to provide a better user experience while recording attendance. No new functionality was added. All focus was on visual feedback and a more intuitive UI. The user no longer needs to check rows before editing them or look through a column of radio buttons.
**UI Improvements**
- New `AttendanceStatusToggle` component to replace the radio buttons with an easier to use toggle button interface for three states: Present, Excused, and Unexcused.
- The values have color-coded buttons (used some opacity so the teal and red weren't as strong) and icons to go with them, along with hover states for interactivity.
- Improved the table layout. The table layout has some better spacing, more accurate column …

fix: refactored attendance page ux

---

frontend/src/Components/LibrarySearchResultsModal.tsx
frontend/src/Components/cards/LibrarySearchResultCard.tsx

This PR fixes the issue with the search functionality of the knowledge center and how the user, particularly on a secure book is/was unable to reach the bottom of the search results, or modal, disallowing them the ability to click on subsequent pages of results. 
- **Related issues**: https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210825285656046?focus=true
27" Monitor
Laptop Monitor Chrome
Chrome Securebook dimensions
Firefox Securebook dimensions
Prior to this PR the LibrarySearchModal had a set modal height, and was placed inside of a dialog element, which as a result stopped the modal from being able to scroll relative to it's parent page, essentially being constrained by the viewport. With a header of approximately 125px, and a footer of approximately 80px, …

fix: knowledge center search modal sizing

---

frontend/src/Components/inputs/TextInput.tsx
frontend/src/Pages/EventAttendance.tsx

[Require the reason field in the UI for Excused/Unexcused attendance](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210842346686462) &
[Clear out notes text input when user selects present on attendance page ](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210801792172853)
https://github.com/user-attachments/assets/68e8d68a-cd3a-4304-9437-d2e5b7984073
Please include any additional context or information that the reviewer may need to …

fix: modified the reason field in the UI for attendance to be required

---

frontend/src/Pages/ResidentProfile.tsx

I added a conditional for checking whether the feature for the Program hub is turned off or on. Based on this condition the Program History/Information is displayed to the user. 
- **Related issues**: Link to related Asana ticket is [Hide Resident Programs info on Resident Tab when Program Hub is turned off](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210958323931677?focus=true)
Program Hub ON
Program Hub OFF
[onoff.webm](https://github.com/user-attachments/assets/bd87fac3-7e8a-4293-aeaa-7a3b4448a102)
NAVIGATION: Login (SuperAdmin) | Click SuperAdmin (popup) | Toggle "Program Hub" Feature On/Off | Click Residents | Click on a resident's name | See table either exists or doesn't

fix: add logic to hide resident programs information when program hub feature is turned off

---

backend/go.mod
backend/go.sum
backend/src/database/class_enrollments.go
backend/src/handlers/class_enrollments.go
backend/src/models/program_classes.go
backend/tests/integration/class_enrollments_test.go
frontend/src/Pages/ClassEnrollmentDetails.tsx

Added the necessary frontend logic to do the following:
- allow the selection of 'Cancelled' when class status is 'Scheduled'
- when class status is 'Active' the status 'Cancelled' will not be an enrollment option
Added the necessary backend logic to do the following:
- rejects the user's request if there is an attempt to set any status that is not allowed.
- **Related issues**: Link to related Asana ticket is: [Limit Enrollment Status Options for Scheduled & Active Classes](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210839726305327?focus=true)
[statuses.webm](https://github.com/user-attachments/assets/f1a26a59-a062-4cce-a158-71416895886b)
NAVIGATION: Login (Admin) | Click Programs | Click Program | Select Class (Active/Scheduled) | Select Enrollment Tab | …

fix: add logic to display enrollment status options based on class status per ticket 394

---

backend/src/database/events_attendance.go
backend/src/handlers/events_attendance_handler.go
frontend/src/Components/AttendanceStatusToggle.tsx
frontend/src/Pages/EventAttendance.tsx

Displays users on the attendance page after a class is canceled or completed. 
- **Related issues**:
https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210787043059218?focus=true
Prior to this ticket the related query was only searching for residents with an enrollment_status of enrolled, this became an issue because once a class is rendered complete, or cancelled, the enrollment_status is then changed to the appropriate status, but is no longer enrolled. This was resulting in a no records found issue in respective classes. We solve this issue by first removing the dependency on an enrolled status and switching to a time based logic. The primary change in terms of the original ticket issue being these LOC's:
```
AND DATE(e.enrolled_at) <= ?::date
AND …
```

fix: attendance renders when complete

---

frontend/src/Pages/HelpfulLinks.tsx

Before this change, when an admin switched to **Preview Student View**, they could still see helpful links that were marked as hidden. Students are only supposed to see links marked as visible, so this was incorrect.  
I fixed this by:  
modifying the query string in the useSWR call, this strategy is similar to that used for 'Preview Student View' on the Libraries/Videos tab 
- **Related issues**: [Link to related Asana ticket that this closes.](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210464235048873)  
---
https://github.com/user-attachments/assets/15dcc214-59b1-408f-bedc-80b0122ef2a2  
---
- Students and admins in student preview see the same limited set of visible links.  
- Admins in admin mode see all links.  
- We used `sessionStorage` instead of …

Hidden Helpful Links appears on admin "preview student view" mode

---

frontend/src/Components/LibrarySearchResultsModal.tsx

Removed the condition that was hiding the suggestion button when search results were found, ensuring the button remains visible whenever a user has entered a search term.
- **Related issues**: Link to related Asana ticket that this closes.
[Suggestion button in Search disappears and reappears after choosing libraries.](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210464235048871)
https://github.com/user-attachments/assets/2dbe49d9-9429-490f-8584-cbcb9aa934fb

fix: Suggestion button visibility in Knowledge Center search

---

frontend/src/Components/TitleManager.tsx

Added some error handling logic to avoid an infinite error loop when viewing specific kiwix library pages within the Knowledge Center. 
- **Related issues**: Link to related Asana ticket that this closes: [Bug: TitleManager Cross-Origin Frame Access Error](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1211317165922357?focus=true)
After fix:
Before fix:
In order to test that this process is working I suggest that you do the following steps:
1. Open kiwix.go on line 23 change it to:  `return 1000`
2. Open up docker-compose.yml on line 85 change url to: `https://kiwix.dev.unlockedlabs.xyz`
3. Open proxy_handler.go on line 45 change `http` to `https`
4. Run the following query against the unlocked database: 
`update open_content_providers set url = …

fix: add try catch block around logic that accesses the document object to avoid error loop per 465

---

frontend/src/Components/LibraryLayout.tsx
frontend/src/Components/LoadingSpinner.tsx
frontend/src/Components/VideoContent.tsx
frontend/src/Pages/HelpfulLinks.tsx
frontend/src/Pages/LibraryViewer.tsx

This PR is the beginning implementation of loading state improvements across the app, it focuses on the Knowledge Center and Library viewer. 
Changes: 
- Added loading spinners to all 3 knowledge center sections
- Implemented iframe loading overlay for the Library Viewer with error handling and a retry functionality 
- Created a reusable loading spinner component 
- **Related issues**:https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210839607709210?focus=true
Current places (including what was updated in this PR) that are arguably all set for loading state: MyCourses.tsx, Favorites.tsx, LibrarySearchResultsModal.tsx, LoginForm.tsx, LibraryLayout.tsx, VideoContent.tsx, HelpfulLinks.tsx, LibraryViewer.tsx
Places that need to be addressed: 
ResidentHome.tsx - Has 3 SWR …

feat: add loading state logic on iframe src evaluate loading state

---

frontend/src/Components/PageNav.tsx
frontend/src/Pages/LibraryViewer.tsx

Added per the asana ticket a **prominent Home button** next to the **Library Title** in the Knowledge Center interface. This button allows users to quickly return to the **main page of the current kiwix library** from any section, article, or deep page, without relying on browser navigation.  Changes involved were just javascript and HTML changes.
- **Related issues**: Link to related Asana ticket that this closes: [Feature: Home Button in Knowledge Center](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1211317165922361?focus=true)
Revision:
If you want a fast way to get some libraries to test with I suggest that you do the following steps:
1. Open kiwix.go on line 23 change it to:  `return 1000`
2. Open up docker-compose.yml on line 85 change url to: …

feat: add home navigation button to Library viewer page per ticket 466

---

frontend/src/Pages/ProgramManagementForm.tsx

- Replace custom label styling with consistent form-control structure
- Use label-text class instead of font-medium to match other form labels
- Maintain tooltip functionality within standardized DaisyUI pattern
- Ensures visual consistency across all form fields (Credit Type, Program Type, etc.)
Fixes inconsistent font sizing where Program Status label appeared larger than other labels on the programs/detail 
- **Related issues**: Link to related Asana ticket that this closes.
[Fix the inconsistency between label font size on `programs/detail`](https://app.asana.com/1/1201607307149189/project/1209460078641109/task/1210535950665361)

fix: standardize Program Status label font size on programs detail page

---

frontend/src/Components/MonthNavigation.tsx
frontend/src/Components/helperFunctions/formatting.tsx
frontend/src/Pages/ClassEvents.tsx

Users were confused by having both calendar dropdown AND pagination controls on the attendance page. The pagination only worked within the selected month, leading users to think earlier classes were missing and attendance percentages were incorrect.
- **Removed** calendar dropdown component
- **Removed** pagination controls that only worked within months  
- **Added** clean month navigation: "← Previous | August 2025 | Next →"
- **Added** "This Month" button for quick navigation
- **Fixed** daily classes to show all events per month (31 max)
- **Added** smart button states based on class date ranges
- Eliminates user confusion about dual navigation
- All events for a month are visible at once
- Clear visual month navigation that users understand
- Accurate attendance tracking across all …

James unlocked/improved attendance page nav
